Repository kiali/kiali-ui, pull requests merged in 2018-03, with the labels that each got.

#92 SWS-258 Separate ServiceDetailInfo components
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoBadge.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoPods.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoRoutes.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoRules.tsx
  src/pages/ServiceDetails/ServiceInfo/index.tsx
  src/types/ServiceInfo.ts
Labels: enhancement

#117 SWS-322 Make service graph text more readable
  src/components/CytoscapeLayout/graphs/GraphStyles.ts
Labels: enhancement

#98 SWS-265: add in loading page for the service graph
  src/components/CytoscapeLayout/CytoscapeLayout.tsx
Labels: enhancement

#125 SWS-316: Add Cose Bilkent and Klay graph type to layouts
  package-lock.json
  package.json
  src/components/CytoscapeLayout/CytoscapeLayout.tsx
  src/components/CytoscapeLayout/ReactCytoscape.tsx
  src/components/CytoscapeLayout/graphs/CoseGraph.ts
  src/components/CytoscapeLayout/graphs/KlayGraph.ts
  src/components/GraphFilter/GraphFilter.tsx
  src/components/GraphFilter/LayoutButtonGroup.tsx
Labels: enhancement

#100 SWS-259 add tests to ServiceDetailInfo
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoRoutes.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoBadge.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoCard.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoDescription.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoPods.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRoutes.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRules.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoBadge.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoCard.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoPods.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRoutes.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRules.test.tsx.snap
  src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/types/ServiceInfo.ts
Labels: Tests

#187 KIALI-427 bump version of ssri.
  package-lock.json
  package.json
Labels: Library Change

#199 [Doc] Update README, add testing information
  README.adoc
Labels: Documentation

#201 [KIALI-170]Iframe with Jaeger
  package-lock.json
  package.json
  src/components/Nav/Navigation.tsx
  src/pages/ServiceJaeger/ServiceJaegerPage.tsx
Labels: enhancement
