Repository kiali/kiali-ui, pull requests merged in 2018-05, with the labels that each got.

#307 Kiali-650: Make the configuration data immutable down the tree.
  package-lock.json
  package.json
  src/config.ts
Labels: Library Change, enhancement

#245 Kiali-345 -Toggle node and edge labels (uses Redux)
  package-lock.json
  package.json
  src/actions/ServiceGraphActions.ts
  src/app/App.tsx
  src/components/CytoscapeLayout/CytoscapeLayout.tsx
  src/components/CytoscapeLayout/__tests__/CytoscapeLayout.test.tsx
  src/components/CytoscapeLayout/graphs/GraphStyles.ts
  src/components/GraphFilter/GraphFilter.tsx
  src/containers/GraphLayers/GraphLayers.tsx
  src/reducers/ServiceGraphState.ts
  src/reducers/__tests__/ServiceGraphStateReducer.test.ts
  src/reducers/index.ts
  src/store/ConfigStore.ts
  src/store/Store.ts
Labels: Library Change, enhancement

#309 KIALI-381: new manual refresh button for metrics screen
  src/components/MetricsOptions/MetricsOptionsBar.tsx
  src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
  src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
  src/pages/ServiceDetails/ServiceMetrics.tsx
Labels: enhancement

#315 KIALI-642 Connects MessageCenter with Redux
  src/actions/MessageCenterActions.ts
  src/actions/index.ts
  src/components/MessageCenter/MessageCenter.tsx
  src/components/MessageCenter/MessageCenterTrigger.tsx
  src/components/MessageCenter/NotificationDrawer.tsx
  src/components/MessageCenter/NotificationList.tsx
  src/components/MessageCenter/StatefulMessageCenter.tsx
  src/components/MessageCenter/__tests__/MessageCenter.test.tsx
  src/components/MessageCenter/index.ts
  src/components/Nav/Navigation.tsx
  src/containers/MessageCenterContainer.tsx
  src/pages/IstioRuleDetails/IstioRuleInfo.tsx
  src/pages/IstioRulesList/IstioRuleListPage.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceGraph/ServiceGraphPage.tsx
  src/pages/ServiceJaeger/ServiceJaegerPage.tsx
  src/pages/ServiceList/ServiceListPage.tsx
  src/reducers/MessageCenter.ts
  src/reducers/index.ts
  src/store/Store.ts
  src/types/MessageCenter.ts
  src/utils/MessageCenter.ts
Labels: enhancement

#319 [KIALI-666] Fix Kiali UI console log error messages
  src/components/GraphFilter/GraphFilter.tsx
  src/components/MetricsOptions/MetricsOptionsBar.tsx
  src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
  src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
  src/components/ToolbarDropdown/ToolbarDropdown.tsx
Labels: bug

#318 Update Project packages for this sprint 5.
  package-lock.json
  package.json
Labels: Library Change, enhancement

#310 Kiali-654: Bring other Service Graph visibility layers into Redux
  package-lock.json
  src/actions/NamespaceAction.ts
  src/actions/ServiceGraphActions.ts
  src/actions/ServiceGraphFilterActions.ts
  src/components/CytoscapeLayout/CytoscapeLayout.tsx
  src/components/CytoscapeLayout/__tests__/CytoscapeLayout.test.tsx
  src/components/GraphFilter/GraphFilter.tsx
  src/containers/GraphLayers/GraphLayers.tsx
  src/pages/ServiceGraph/ServiceGraphPage.tsx
  src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx
  src/pages/ServiceGraph/__tests__/ServiceGraphPage.test.tsx
  src/reducers/Namespaces.ts
  src/reducers/ServiceGraphFilterState.ts
  src/reducers/ServiceGraphState.ts
  src/reducers/__tests__/ServiceGraphFilterStateReducer.test.ts
  src/reducers/__tests__/ServiceGraphStateReducer.test.ts
  src/reducers/index.ts
  src/store/Store.ts
  src/types/Graph.ts
  src/types/GraphFilter.ts
  src/utils/Reducer.ts
Labels: Refactor, enhancement

#324 Add ActionCreator tests to test the Actions
  src/actions/ServiceGraphFilterActions.ts
  src/actions/__tests__/GraphFilterAction.test.tsx
  src/reducers/ServiceGraphFilterState.ts
Labels: Tests

#320 [KIALI-692] Tests for ToolbarDropdown Component
  src/components/ToolbarDropdown/ToolbarDropdown.tsx
  src/components/ToolbarDropdown/__tests__/ToolbarDropdown.test.tsx
  src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
Labels: Tests, enhancement

#331 Kiali-722 Fix top margin by moving from 230px to 170px.
  src/pages/ServiceGraph/ServiceGraphPage.tsx
Labels: bug

#348 KIALI-727 Migrate from npm to yarn
  .gitignore
  .npmrc
  .travis.yml
  README.adoc
  package-lock.json
  package.json
  run_itest.sh
  src/app/App.scss
  yarn.lock
Labels: Do NOT Merge (yet), Library Change, bug

#356 KIALI-752 Show traffic/latency as dots passing in the edges of the service graph
  package.json
  src/actions/ServiceGraphFilterActions.ts
  src/actions/__tests__/GraphFilterAction.test.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/CytoscapeGraph/graphs/GraphHighlighter.ts
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/CytoscapeGraph/graphs/TrafficRenderer.ts
  src/containers/GraphLayersContainer.tsx
  src/reducers/ServiceGraphFilterState.ts
  src/reducers/__tests__/ServiceGraphFilterStateReducer.test.ts
  src/store/Store.ts
  src/utils/MathUtils.ts
  src/utils/__tests__/MathUtils.test.ts
  yarn.lock
Labels: enhancement

#361 [KIALI-153] Show Graph legend
  package.json
  src/actions/ServiceGraphDataActions.ts
  src/components/Badge/__tests__/Badge.test.tsx
  src/components/Details/DetailObject.tsx
  src/components/GraphFilter/GraphFilter.tsx
  src/components/GraphFilter/GraphFilterToolbar.tsx
  src/components/GraphFilter/GraphLegend.tsx
  src/components/GraphFilter/__tests__/GraphFilterToolbar.test.tsx
  src/components/GraphFilter/__tests__/GraphLegend.test.tsx
  src/components/GraphFilter/__tests__/__snapshots__/GraphLegend.test.tsx.snap
  src/components/ServiceHealth/HealthHelper.tsx
  src/components/SummaryPanel/InOutRateChart.tsx
  src/components/SummaryPanel/LatencyChart.tsx
  src/components/SummaryPanel/RateChart.tsx
  src/components/SummaryPanel/RpsChart.tsx
  src/containers/ServiceGraphPageContainer.ts
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDeployments.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoRouteRules/RouteRuleRoute.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoCard.test.tsx
  src/pages/ServiceGraph/ServiceGraphPage.tsx
  src/pages/ServiceGraph/SummaryPanelEdge.tsx
  src/pages/ServiceGraph/SummaryPanelGroup.tsx
  src/pages/ServiceGraph/SummaryPanelNode.tsx
  src/reducers/ServiceGraphDataState.ts
  src/reducers/__tests__/ServiceGraphDataState.test.ts
  src/services/__mockData__/getGraphElements.ts
  src/store/Store.ts
  src/types/GraphFilterToolbar.ts
  yarn.lock
Labels: enhancement

#352 Reduxify the PfSpinner
  src/actions/GlobalActions.ts
  src/app/App.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/Pf/PfSpinner.tsx
  src/containers/PfSpinnerContainer.tsx
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
  src/reducers/GlobalState.ts
  src/reducers/__tests__/GlobalStateReducer.test.ts
  src/reducers/index.ts
  src/store/Store.ts
Labels: Refactor

#382 Kiali-841 Standardize the isLoading Spinner to Header
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/Nav/Navigation.tsx
  src/containers/PfSpinnerContainer.tsx
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
Labels: enhancement

#314 [KIALI-534] Login
  src/__itests__/App.browser.test.tsx
  src/actions/LoginActions.ts
  src/actions/NamespaceAction.ts
  src/actions/ServiceGraphDataActions.ts
  src/actions/__tests__/LoginAction.test.ts
  src/app/App.tsx
  src/components/About/AboutUIModal.tsx
  src/components/NamespaceFilter/NamespaceFilter.tsx
  src/components/Nav/Navigation.tsx
  src/components/Nav/UserDropdown.tsx
  src/components/Nav/__tests__/Navigation.test.tsx
  src/components/SocialLink/SocialLink.tsx
  src/components/SocialLink/__tests__/SocialLink.test.tsx
  src/components/SocialLink/__tests__/__snapshots__/SocialLink.test.tsx.snap
  src/config.ts
  src/containers/LoginPageContainer.ts
  src/containers/NavigationContainer.ts
  src/containers/UserDropdownContainer.ts
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/Login/__tests__/LoginPage.test.tsx
  src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceMetrics.tsx
  src/pages/ServiceGraph/SummaryPanelEdge.tsx
  src/pages/ServiceGraph/SummaryPanelGraph.tsx
  src/pages/ServiceGraph/SummaryPanelGroup.tsx
  src/pages/ServiceGraph/SummaryPanelNode.tsx
  src/pages/ServiceJaeger/ServiceJaegerPage.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
  src/reducers/LoginState.ts
  src/reducers/index.ts
  src/services/Api.ts
  src/services/__tests__/ApiMethods.test.tsx.ts
  src/store/Store.ts
  src/utils/Authentication.ts
  src/utils/__tests__/Authentication.test.ts
Labels: enhancement

#383 Kiali-848 Remove Redux Logger (too verbose)
  package.json
  src/store/ConfigStore.ts
  yarn.lock
Labels: Library Change

#289 [KIALI-599] Code style guide
  README.adoc
  STYLE_GUIDE.adoc
Labels: Documentation

#381 KIALI-762 - Force Jest to exit after all tests have completed running
  .travis.yml
Labels: Tests

#384 [KIALI-846] Show Error Connecting to Kiali when there is a 404 code
  src/reducers/LoginState.ts
Labels: bug

#386 KIALI-745 Autoupdate the service graph
  src/actions/ServiceGraphDataActions.ts
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/Filters/PollIntervalFilter.tsx
  src/components/GraphFilter/GraphFilter.tsx
  src/components/GraphFilter/GraphFilterToolbar.tsx
  src/components/GraphFilter/__tests__/GraphFilterToolbar.test.tsx
  src/components/MetricsOptions/MetricsOptionsBar.tsx
  src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
  src/components/Nav/NavUtils.tsx
  src/pages/ServiceGraph/ServiceGraphPage.tsx
  src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx
  src/reducers/ServiceGraphDataState.ts
  src/types/Graph.ts
  src/types/GraphFilter.ts
Labels: bug, enhancement
