Repository kiali/kiali-ui, pull requests merged in 2018-11, with the labels that each got.

#782 KIALI-1821 Add delete action in Service > Istio details
  src/components/IstioActions/IstioActionsDropdown.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/pages/ServiceDetails/IstioObjectDetails.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/services/__mockData__/getServiceDetail.json
  src/services/__tests__/Api.test.tsx
  src/types/IstioConfigList.ts
  src/types/Permissions.ts
  src/types/ServiceInfo.ts
Labels: PR Required

#833 KIALI-1948 Split Istio Rules in Rules/Adapters/Templates
  src/config.ts
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.scss
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigDetails/IstioRuleInfo.tsx
  src/pages/IstioConfigList/FiltersAndSorts.ts
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/routes.tsx
  src/services/Api.ts
  src/types/IstioConfigDetails.ts
  src/types/IstioConfigList.ts
  src/types/IstioRuleInfo.ts
Labels: PR Required

#840 KIALI-1802 Make DestinationRule in service details clickable and navigate to Istio Config
  src/pages/ServiceDetails/IstioObjectDetails.tsx
  src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/DestinationRuleDetail.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
Labels: Do NOT Merge (yet)

#841 KIALI-1985 Refactor IstioObjects to map metadata/spec properly
  src/components/Details/__tests__/DetailObject.test.tsx
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/pages/ServiceDetails/IstioObjectDetails.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/DestinationRuleDetail.tsx
  src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/VirtualServiceDetail.tsx
  src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/VirtualServiceRoute.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRouteVirtualServices.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/services/__mockData__/getIstioConfigBookinfo.json
  src/services/__mockData__/getIstioConfigDetail.json
  src/services/__mockData__/getServiceDetail.json
  src/services/__tests__/Api.test.tsx
  src/types/IstioConfigDetails.ts
  src/types/IstioConfigList.ts
  src/types/IstioObjects.ts
  src/types/ServiceInfo.ts
Labels: PR Required

#839 KIALI-1140 Adding destination services into WorkloadDetails page
  src/components/InfoRoutes/InfoRoutes.tsx
  src/components/InfoRoutes/ServiceInfoRoutes.tsx
  src/components/InfoRoutes/WorkloadInfoRoutes.tsx
  src/components/InfoRoutes/__tests__/ServiceInfoRoutes.test.tsx
  src/components/InfoRoutes/__tests__/__snapshots__/ServiceInfoRoutes.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRoutes.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRoutes.test.tsx.snap
  src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/types/ServiceInfo.ts
  src/types/Workload.ts
Labels: PR Required

#846 KIALI-1918 Add @types/react-redux dev-package
  package.json
  src/actions/GlobalActions.ts
  src/actions/GrafanaActions.ts
  src/actions/GrafanaThunkActions.ts
  src/actions/GraphActions.ts
  src/actions/GraphDataActionKeys.ts
  src/actions/GraphDataActions.ts
  src/actions/GraphDataThunkActions.ts
  src/actions/GraphThunkActions.ts
  src/actions/HelpDropdownActions.ts
  src/actions/HelpDropdownThunkActions.ts
  src/actions/LoginActions.ts
  src/actions/LoginThunkActions.ts
  src/actions/MessageCenterActions.ts
  src/actions/MessageCenterThunkActions.ts
  src/actions/NamespaceAction.ts
  src/actions/NamespaceThunkActions.ts
  src/actions/UserSettingsActions.ts
  src/actions/UserSettingsThunkActions.ts
  src/actions/__tests__/GraphActions.test.ts
  src/actions/__tests__/MessageCenterAction.test.ts
  src/actions/__tests__/NamespaceAction.test.ts
  src/app/App.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/CytoscapeToolbar.tsx
  src/components/GraphFilter/GraphFilter.tsx
  src/components/GraphFilter/GraphRefresh.tsx
  src/components/GraphFilter/GraphSettings.tsx
  src/components/Metrics/Metrics.tsx
  src/components/Metrics/__tests__/Metrics.test.tsx
  src/components/Metrics/__tests__/__snapshots__/Metrics.test.tsx.snap
  src/components/NamespaceDropdown.tsx
  src/components/Nav/Navigation.tsx
  src/components/Nav/__tests__/Navigation.test.tsx
  src/containers/EmptyGraphLayoutContainer.tsx
  src/containers/GraphPageContainer.ts
  src/containers/LoginPageContainer.ts
  src/containers/MessageCenterContainer.tsx
  src/containers/NavigationContainer.ts
  src/containers/OverviewPageContainer.ts
  src/containers/RefreshContainer.tsx
  src/containers/UserDropdownContainer.ts
  src/pages/Graph/GraphPage.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/Overview/OverviewPage.tsx
  src/pages/Overview/OverviewToolbar.tsx
  src/reducers/MessageCenter.ts
  src/reducers/__tests__/GlobalStateReducer.test.ts
  src/reducers/__tests__/GraphDataState.test.ts
  src/reducers/__tests__/MessageCenterReducer.test.ts
  src/reducers/__tests__/NamespacesReducer.test.ts
  src/reducers/__tests__/UserSettingsState.test.ts
  src/services/Api.ts
  src/store/Store.ts
  src/types/Graph.ts
  src/types/MetricsOptions.ts
  yarn.lock
Labels: Library Change

#851 KIALI-1140 Add destination services for workload details endpoint
  src/components/InfoRoutes/InfoRoutes.tsx
  src/components/InfoRoutes/ServiceInfoRoutes.tsx
  src/components/InfoRoutes/WorkloadInfoRoutes.tsx
  src/components/InfoRoutes/__tests__/ServiceInfoRoutes.test.tsx
  src/components/InfoRoutes/__tests__/__snapshots__/ServiceInfoRoutes.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoRoutes.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRoutes.test.tsx.snap
  src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/types/ServiceInfo.ts
  src/types/Workload.ts
Labels: PR Required
