Repository kiali/kiali-ui, pull requests merged in 2018-12, with the labels that each got.

#863 KIALI-2076: Upgrade typescript and prettier
  package.json
  src/components/Filters/StatefulFilters.tsx
  src/components/Health/HealthIndicator.tsx
  src/components/MessageCenter/NotificationDrawer.tsx
  src/components/Metrics/__tests__/Metrics.test.tsx
  src/components/SessionTimeout/SessionTimeout.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigList/FiltersAndSorts.ts
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
  src/services/__mockData__/getServiceDetail.json
  src/store/Selectors.ts
  src/types/ServiceInfo.ts
  yarn.lock
Labels: Library Change

#865 Trivial: Remove 'coveralls' library since we no longer do coverage
  package.json
  yarn.lock
Labels: Library Change

#871 KIALI-2086 More optimized metrics API
  src/components/Metrics/Metrics.tsx
  src/components/Metrics/__tests__/Metrics.test.tsx
  src/components/MetricsOptions/MetricsOptionsBar.tsx
  src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
  src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/services/__mocks__/Api.ts
  src/services/__tests__/ApiMethods.test.tsx.ts
  src/types/Metrics.ts
  src/types/MetricsOptions.ts
Labels: PR Required

#875 KIALI-2109 Snyk install for vulnerability remediation
  .snyk
  package.json
  yarn.lock
Labels: Library Change

#876 KIALI-2129 UXD: Move the grafana link to the topbar
  src/actions/LoginThunkActions.ts
  src/components/GraphFilter/GraphRefresh.tsx
  src/components/Metrics/Metrics.tsx
  src/components/MetricsOptions/MetricsOptionsBar.tsx
  src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
  src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
  src/components/Refresh/Refresh.tsx
  src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
  src/config/config.ts
  src/containers/WorkloadMetricsContainer.tsx
Labels: ux-review

#887 KIALI-2110 Updates to cytoscape 3.3.1
  package.json
  yarn.lock
Labels: Library Change :books:

#890 KIALI-2158 Update husky and remove deprecation error
  package.json
  yarn.lock
Labels: Library Change :books:
