Repository kiali/kiali-ui, pull requests merged in 2018-09, with the labels that each got.

#637 KIALI-1443 Ensure RCUE is loaded only when demanded
  package.json
  src/app/App.tsx
Labels: Do NOT Merge (yet)

#643 KIALI-1466 Session timeout dialog box shows negative seconds remaining for timeout
  src/components/Nav/UserDropdown.tsx
Labels: bug

#669 KIALI-980 :First of our low risk library updates including: cytoscape
  package.json
  yarn.lock
Labels: Library Change

#683 KIALI-1555: Update the Redux packages to latest 4.0.0
  package.json
  src/store/ConfigStore.ts
  yarn.lock
Labels: Library Change

#691 KIALI-1526 Don't display links in side panel for egress nodes
  src/pages/Graph/SummaryPanelCommon.tsx
Labels: Do NOT Merge (yet)

#703 KIALI-1598 Support service detail graphs
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/Nav/NavUtils.tsx
  src/pages/Graph/GraphRouteHandler.tsx
  src/routes.tsx
  src/services/Api.ts
  src/types/Graph.ts
Labels: Do NOT Merge (yet)
