Repository kiali/kiali-ui, pull requests merged in 2018-08, with the labels that each got.

#553 KIALI-1279 Avoid Kiali lock-up by multiple chart refreshes when page …
  package.json
  src/actions/GlobalActions.ts
  src/actions/__tests__/GlobalActions.test.ts
  src/app/App.tsx
  src/containers/ServiceGraphPageContainer.ts
  src/pages/ServiceGraph/ServiceGraphPage.tsx
  src/pages/ServiceGraph/SummaryPanel.tsx
  src/reducers/GlobalState.ts
  src/reducers/__tests__/GlobalStateReducer.test.ts
  src/store/Store.ts
  yarn.lock
Labels: Library Change

#554 KIALI-1289 NameSpaceFilter is not working when the initialFilters is []
  src/components/NamespaceFilter/NamespaceFilter.tsx
Labels: bug

#555 KIALI-1216 Add a new Workload list page.
  src/components/NamespaceFilter/NamespaceFilter.tsx
  src/config.ts
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
  src/pages/WorkloadList/FiltersAndSorts.ts
  src/pages/WorkloadList/WorkloadListClass.tsx
  src/pages/WorkloadList/WorkloadListComponent.tsx
  src/pages/WorkloadList/WorkloadListPage.tsx
  src/routes.tsx
  src/services/Api.ts
  src/types/ServiceListComponent.ts
  src/types/Workload.ts
Labels: Do NOT Merge (yet), enhancement

#587 KIALI-1218 Service details: Pods and deployments removed + adding workloads
  src/components/Pf/PfInfoCard.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDeployments.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoDeployments.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoWorkloads.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoCard.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDeployments.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
  src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/pages/ServiceList/ServiceListComponent.scss
  src/services/Api.ts
  src/types/ServiceInfo.ts
Labels: PR Required

#593 KIALI-1367 Breadcrumb throw an error in console
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
Labels: bug

#592 KIALI-1217 Add a new Workload details page
  src/components/ConfigValidation/ConfigIndicator.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/ServiceDetails/IstioObjectDetails.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/VirtualServiceDetail.tsx
  src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/VirtualServiceRoute.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoPods.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoPodsGrouping.ts
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoPods.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoPodsGrouping.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoWorkloads.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadServices.tsx
  src/pages/WorkloadList/WorkloadListClass.tsx
  src/routes.tsx
  src/services/Api.ts
  src/types/AceValidations.ts
  src/types/IstioConfigListComponent.ts
  src/types/IstioObjects.ts
  src/types/ServiceInfo.ts
  src/types/Workload.ts
  src/types/__tests__/AceValidations.test.ts
Labels: enhancement

#601 KIALI-1240 Add a new App list page
  src/pages/AppList/AppListClass.tsx
  src/pages/AppList/AppListComponent.tsx
  src/pages/AppList/AppListPage.tsx
  src/pages/AppList/FiltersAndSorts.ts
  src/routes.tsx
  src/services/Api.ts
  src/types/AppList.ts
Labels: Do NOT Merge (yet)

#604 KIALI-1323 Filtering homogenization
  src/components/NamespaceFilter/NamespaceFilter.tsx
  src/pages/AppList/AppListComponent.tsx
  src/pages/AppList/FiltersAndSorts.ts
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
  src/pages/WorkloadList/FiltersAndSorts.ts
  src/pages/WorkloadList/WorkloadListComponent.tsx
  src/types/NamespaceFilter.ts
Labels: Do NOT Merge (yet)

#605 KIALI-1389 Fix edge sparklines
  src/components/Metrics/Metrics.tsx
  src/components/Metrics/__tests__/Metrics.test.tsx
  src/pages/ServiceGraph/SummaryPanelCommon.tsx
  src/pages/ServiceGraph/SummaryPanelEdge.tsx
  src/pages/ServiceGraph/SummaryPanelGraph.tsx
  src/pages/ServiceGraph/SummaryPanelGroup.tsx
  src/pages/ServiceGraph/SummaryPanelNode.tsx
  src/types/Metrics.ts
  src/types/MetricsOptions.ts
  src/utils/Graphing.ts
Labels: Do NOT Merge (yet), PR Required

#602 KIALI-1376 Update Workload list and Workload details with WorkloadHealth
  src/pages/ServiceList/ItemDescription.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/pages/WorkloadList/ErrorRate.tsx
  src/pages/WorkloadList/FiltersAndSorts.ts
  src/pages/WorkloadList/ItemDescription.tsx
  src/pages/WorkloadList/WorkloadListClass.tsx
  src/pages/WorkloadList/WorkloadListComponent.tsx
  src/pages/WorkloadList/WorkloadListPage.tsx
  src/types/Workload.ts
Labels: Do NOT Merge (yet)

#606 KIALI-1117 Create a Dialog Box to warn user about session Timeout
  src/actions/LoginActions.ts
  src/components/Nav/UserDropdown.tsx
  src/components/SessionTimeout/SessionTimeout.tsx
  src/config.ts
  src/containers/UserDropdownContainer.ts
  src/reducers/LoginState.ts
Labels: enhancement

#618 KIALI-1409 Metrics - Duration select and Poll Interval - Too close
  src/components/ToolbarDropdown/ToolbarDropdown.tsx
  src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
Labels: bug

#626 KIALI-1145 Add VirtualService TLS routes to details page
  src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/VirtualServiceDetail.tsx
  src/types/ServiceInfo.ts
Labels: PR Required

#619 KIALI-1423 Move Jaeger iFrame to external links
  src/components/Nav/Navigation.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
Labels: Do NOT Merge (yet), PR Required
