Repository kiali/kiali-ui, pull requests merged in 2018-06, with the labels that each got.

#393 KIALI-861 Prepare service graph for refreshing
  src/actions/ServiceGraphDataActions.ts
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/GraphFilter/GraphFilter.tsx
  src/pages/ServiceGraph/SummaryPanelCommon.ts
  src/pages/ServiceGraph/SummaryPanelEdge.tsx
  src/pages/ServiceGraph/SummaryPanelGraph.tsx
  src/pages/ServiceGraph/SummaryPanelGroup.tsx
  src/pages/ServiceGraph/SummaryPanelNode.tsx
  src/reducers/ServiceGraphDataState.ts
Labels: bug

#420 Fix login, check the token is still valid after refresh
  src/actions/LoginActions.ts
  src/components/Nav/Navigation.tsx
  src/components/Nav/__tests__/Navigation.test.tsx
  src/config.ts
  src/containers/NavigationContainer.ts
  src/pages/Login/LoginPage.tsx
  src/pages/Login/__tests__/LoginPage.test.tsx
  src/services/Api.ts
  src/types/Common.ts
Labels: bug

#424 Changed name products by External Services
  src/components/About/AboutUIModal.tsx
Labels: Do NOT Merge (yet)

#423 Trivial Remove 'General' section from readme it is not relevant.
  README.adoc
Labels: Documentation

#421 [KIALI-902] Improve itest bot to fetch images on demand
  getLabels.py
  run_itest.sh
  src/__itests__/App.browser.test.tsx
  take_test_screenshot.sh
Labels: kiali-bot-graph, kiali-bot-istio

#427 KIALI-757: Add expand feature in the detailed metrics page
  src/pages/ServiceDetails/HistogramChart.tsx
  src/pages/ServiceDetails/MetricChart.tsx
  src/pages/ServiceDetails/MetricsChartBase.tsx
  src/pages/ServiceDetails/ServiceMetrics.tsx
Labels: enhancement

#470 KIALI-992 Use public methods instead of the private internal data for…
  package.json
  src/components/CytoscapeGraph/graphs/TrafficRenderer.ts
  yarn.lock
Labels: Library Change, enhancement

#475 KIALI-1033 Fix duplicates in filtering in ServiceList
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
  src/utils/Common.ts
  src/utils/__tests__/Common.test.ts
Labels: bug

#473 KIALI-998 Don't ignore groups, instead detect if we have child nodes …
  src/components/CytoscapeGraph/graphs/GraphHighlighter.ts
Labels: bug
