Repository kiali/kiali-ui, pull requests merged in 2018-04, with the labels that each got.

#206 Kiali-429 Fix Collapse Menu
  src/components/Nav/Navigation.tsx
Labels: bug

#126 Adds storybook for some components
  .storybook/config.js
  package-lock.json
  package.json
  src/components/CytoscapeLayout/CytoscapeLayout.stories.tsx
  src/components/CytoscapeLayout/__stories__/bookinfo.json
  src/components/MetricsOptions/MetricsOptions.stories.tsx
  src/components/NamespaceFilter/NamespaceFilter.stories.tsx
  src/components/NamespaceFilter/NamespaceFilter.tsx
  src/components/Pf/Pf.stories.tsx
  stories/index.stories.js
  storybook/addons.js
  storybook/config.js
  storybook/webpack.config.js
  tsconfig.json
Labels: enhancement

#210 KIALI-126 Refresh Metrics
  src/components/MetricsOptions/MetricsOptionsBar.tsx
  src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
  src/pages/ServiceDetails/ServiceMetrics.tsx
  src/pages/ServiceDetails/__tests__/ServiceMetrics.test.tsx
Labels: enhancement

#213 Kiali-484: Upgrade to typescript 2.8.1 from 2.7.2
  package-lock.json
  package.json
Labels: Library Change

#209 App test: setup mocks to avoid error while getting namespaces
  src/app/__tests__/App.test.tsx
Labels: Tests

#214 Kiali-486: Upgrade to React 16.3.1 from 16.2.0
  package-lock.json
  package.json
  src/components/MetricsOptions/MetricsOptionsBar.tsx
  src/components/NamespaceFilter/NamespaceFilter.tsx
  src/pages/IstioRuleDetails/IstioRuleInfo.tsx
  src/pages/IstioRulesList/IstioRuleListComponent.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceJaeger/ServiceJaegerPage.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
Labels: Library Change, Refactor

#221 KIALI-358 Wraps Switch into an ErrorBoundary object
  src/components/Nav/Navigation.tsx
  src/components/SwitchErrorBoundary/SwitchErrorBoundary.tsx
Labels: enhancement

#225 Trivial: Cosmetic. Make Height 100% in EmptyGraphLayout
  src/components/CytoscapeLayout/EmptyGraphLayout.tsx
Labels: enhancement

#244 KIALI-520 replace 'Refresh' button
  src/components/GraphFilter/DurationButtonGroup.tsx
  src/components/GraphFilter/GraphFilter.tsx
  src/components/GraphFilter/LayoutButtonGroup.tsx
  src/pages/ServiceGraph/ServiceGraphPage.tsx
  src/types/GraphFilter.ts
Labels: Refactor

#255 Trivial: Cleanup null checks. Use more readable truthy checks.
  src/components/CytoscapeLayout/CytoscapeLayout.tsx
Labels: Refactor

#253 Kiali-561 Update package.json libraries for sprint 4
  package-lock.json
  package.json
Labels: Library Change

#258 [KIALI-528] Change GraphFilter DurantionButtonGroup by DurationDropdown
  src/components/CytoscapeLayout/__tests__/CytoscapeLayout.test.tsx
  src/components/GraphFilter/DurationButtonGroup.tsx
  src/components/GraphFilter/DurationDropdown.tsx
  src/components/GraphFilter/GraphFilter.tsx
  src/components/GraphFilter/LayoutButtonGroup.tsx
  src/components/GraphFilter/LayoutDropdown.tsx
  src/components/GraphFilter/QueryOptions.ts
  src/types/GraphFilter.ts
Labels: Refactor, enhancement

#275 [KIALI-607] Add labels and state to dropdowns in Graph toolbar
  src/components/GraphFilter/DurationDropdown.tsx
  src/components/GraphFilter/GraphFilter.tsx
  src/components/GraphFilter/LayoutDropdown.tsx
  src/components/ToolbarDropdown/ToolbarDropdown.tsx
Labels: Refactor, enhancement

#293 Remove all binding by arrow methods
  src/components/Badge/Badge.tsx
  src/components/CytoscapeLayout/CytoscapeLayout.tsx
  src/components/MetricsOptions/MetricsOptionsBar.tsx
  src/components/MetricsOptions/ValueSelectHelper.tsx
  src/components/NamespaceFilter/NamespaceFilter.tsx
  src/pages/IstioRulesList/IstioRuleListPage.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
  src/pages/ServiceList/ServiceListPage.tsx
Labels: Refactor

#288 [KIALI-610] Shared app duration option in toolbars
  src/components/GraphFilter/GraphFilter.tsx
  src/components/MetricsOptions/MetricsOptionsBar.tsx
  src/components/MetricsOptions/__tests__/MetricsOptionsBar.test.tsx
  src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
  src/components/ToolbarDropdown/ToolbarDropdown.tsx
  src/config.ts
  src/pages/ServiceGraph/ServiceGraphPage.tsx
Labels: enhancement

#302 [KIALI-610] Fix onClick in Toolbar Component
  src/components/GraphFilter/GraphFilter.tsx
  src/components/MetricsOptions/MetricsOptionsBar.tsx
  src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
  src/components/ToolbarDropdown/ToolbarDropdown.tsx
Labels: bug

#292 Package libraries versions bump
  package-lock.json
  package.json
Labels: Library Change

#305 KIALI-627 nameaspace label (part two)
  src/components/GraphFilter/GraphFilter.tsx
Labels: enhancement

#306 Trivial: Enclose table content into <tbody>
  src/pages/ServiceList/ServiceListComponent.tsx
Labels: enhancement
