Repository kiali/kiali-ui, pull requests merged in 2018-07, with the labels that each got.

#483 Trivial: Use action creators instead of dispatching actions for spinner
  src/app/App.tsx
Labels: Refactor

#404 KIALI-269 Warning Message when the Istio version is not supported
  src/actions/HelpDropdownActions.ts
  src/actions/LoginActions.ts
  src/components/About/AboutUIModal.tsx
  src/components/MessageCenter/MessageCenterTrigger.tsx
  src/components/Nav/HelpDropdown.tsx
  src/components/Nav/Navigation.tsx
  src/containers/HelpDropdownContainer.ts
  src/reducers/HelpDropdownState.ts
  src/reducers/index.ts
  src/store/Store.ts
Labels: Refactor, enhancement

#495 KIALI-1103 Fix versions components in about and refactor
  src/actions/HelpDropdownActions.ts
  src/services/Api.ts
  src/services/__tests__/ApiMethods.test.tsx.ts
  src/store/ConfigStore.ts
Labels: Refactor, bug

#496 KIALI-533 Session Timeout
  src/actions/LoginActions.ts
  src/actions/NamespaceAction.ts
  src/actions/__tests__/LoginAction.test.ts
  src/config.ts
  src/pages/Login/LoginPage.tsx
  src/reducers/LoginState.ts
  src/store/Store.ts
Labels: enhancement

#497 KIALI-1071 Remember state of left-nav menu
  src/actions/UserSettingsActions.ts
  src/components/Nav/Navigation.tsx
  src/components/Nav/__tests__/Navigation.test.tsx
  src/containers/NavigationContainer.ts
  src/reducers/UserSettingsState.ts
  src/reducers/index.ts
  src/store/ConfigStore.ts
  src/store/Store.ts
Labels: enhancement

#494 KIALI-1082 Allow the graph to grow to the left and right
  package.json
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
  src/components/GraphFilter/GraphLegend.tsx
  src/components/GraphFilter/__tests__/__snapshots__/GraphLegend.test.tsx.snap
  src/pages/ServiceGraph/ServiceGraphPage.tsx
  src/pages/ServiceGraph/SummaryPanelEdge.tsx
  src/pages/ServiceGraph/SummaryPanelGraph.tsx
  src/pages/ServiceGraph/SummaryPanelGroup.tsx
  src/pages/ServiceGraph/SummaryPanelNode.tsx
  yarn.lock
Labels: Library Change, enhancement

#506 KIALI-1119 Nodes from other namespaces now show their version
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
Labels: Do NOT Merge (yet)

#435 KIALI-931: UXD toolbar refactor for Display settings and badges
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/GraphFilter/GraphFilter.tsx
  src/components/GraphFilter/GraphFilterToolbar.tsx
  src/components/GraphFilter/__tests__/GraphFilterToolbar.test.tsx
  src/components/Nav/NavUtils.tsx
  src/components/ToolbarDropdown/EdgeLabelRadioGroup.tsx
  src/containers/GraphLayersContainer.tsx
  src/containers/GraphSettingsContainer.tsx
  src/pages/ServiceGraph/ServiceGraphRouteHandler.tsx
  src/reducers/ServiceGraphFilterState.ts
  src/reducers/__tests__/ServiceGraphFilterStateReducer.test.ts
  src/store/Store.ts
Labels: enhancement

#503 KIALI-1114 Allow IstioConfig list show warning messages
  src/components/ConfigValidation/ConfigIndicator.tsx
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/types/IstioConfigListComponent.ts
Labels: bug

#513 KIALI-1159 FIX Refreshing kiali always redirects to service graph
  src/app/History.tsx
  src/components/Nav/Navigation.tsx
  src/components/Nav/RenderPage.tsx
  src/components/Nav/__tests__/Navigation.test.tsx
  src/routes.tsx
  src/types/Routes.ts
Labels: Refactor, bug

#522 KIALI-1177 Fix refresh issue. Basepath was not being set.
  package.json
  src/actions/MessageCenterActions.ts
  src/actions/ServiceGraphActions.ts
  src/actions/ServiceGraphDataActionKeys.ts
  src/actions/ServiceGraphDataActions.ts
  src/app/History.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/graphs/GraphHighlighter.ts
  src/components/GraphFilter/GraphFilter.tsx
  src/components/Nav/NavUtils.tsx
  src/components/Nav/__tests__/Navigation.test.tsx
  src/components/ToolbarDropdown/EdgeLabelRadioGroup.tsx
  src/containers/GraphSettingsContainer.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigDetails/IstioRuleInfo.tsx
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
  src/pages/ServiceGraph/SummaryPanelEdge.tsx
  src/pages/ServiceGraph/SummaryPanelGraph.tsx
  src/pages/ServiceGraph/SummaryPanelGroup.tsx
  src/pages/ServiceGraph/SummaryPanelNode.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
  src/reducers/ServiceGraphDataState.ts
  src/routes.tsx
  src/types/Graph.ts
  src/types/IstioConfigDetails.ts
  src/utils/MessageCenter.ts
  tslint.json
  yarn.lock
Labels: Library Change, bug

#530 KIALI-1220 Fix link to yaml in DestinationRule
  src/pages/ServiceDetails/IstioObjectDetails.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
Labels: bug

#517 KIALI-1166 Only update EmptyGraphLayout when needed
  src/components/CytoscapeGraph/EmptyGraphLayout.tsx
Labels: bug
