Repository kiali/kiali-ui, pull requests merged in 2018-10, with the labels that each got.

#718 KIALI-1534 Introduce Service Graph
  src/components/SummaryPanel/ResponseTimeChart.tsx
  src/components/SummaryPanel/RpsChart.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/types/Graph.ts
Labels: Do NOT Merge (yet)

#687 KIALI-1284 Update Health to use Workloads instead Deployments
  src/components/Health/__tests__/HealthIndicator.test.tsx
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/pages/AppDetails/AppInfo/AppDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoPods.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoPodsGrouping.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoPods.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
  src/pages/WorkloadList/FiltersAndSorts.ts
  src/pages/WorkloadList/ItemDescription.tsx
  src/services/Api.ts
  src/types/Health.ts
  src/types/IstioObjects.ts
  src/types/Workload.ts
  src/types/__tests__/Health.test.ts
Labels: PR Required

#730 KIALI-1337: Keep Namespace selection consistent when navigating
  package.json
  src/actions/NamespaceAction.ts
  src/actions/__tests__/NamespaceAction.test.ts
  src/app/History.ts
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/GraphFilter/GraphFilterToolbar.tsx
  src/components/NamespaceDropdown.tsx
  src/components/Nav/NavUtils.tsx
  src/components/Nav/Navigation.scss
  src/components/Nav/Navigation.tsx
  src/components/ToolbarDropdown/ToolbarDropdown.tsx
  src/containers/GraphSettingsContainer.tsx
  src/containers/NamespaceDropdownContainer.tsx
  src/containers/OverviewPageContainer.ts
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphRouteHandler.tsx
  src/pages/Overview/OverviewPage.tsx
  src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
  src/reducers/NamespaceState.ts
  src/reducers/Namespaces.ts
  src/reducers/__tests__/NamespacesReducer.test.ts
  src/reducers/index.ts
  src/routes.tsx
  src/store/ConfigStore.ts
  src/store/Selectors.ts
  src/store/Store.ts
  src/types/Common.ts
  src/utils/MessageCenter.ts
  yarn.lock
Labels: Library Change

#753 Kiali-1553 upgrade React library to 16.5.2
  package.json
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/GraphFilter/GraphFilter.tsx
  src/components/GraphFilter/GraphFilterToolbar.tsx
  src/components/NamespaceDropdown.tsx
  src/components/Nav/Navigation.tsx
  src/components/ToolbarDropdown/ToolbarDropdown.tsx
  src/containers/GraphSettingsContainer.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphRouteHandler.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/Overview/OverviewPage.tsx
  src/types/Routes.ts
  tsconfig.prod.json
  yarn.lock
Labels: Do NOT Merge (yet)

#734 KIALI-1701 Move API URLs to a config file
  src/config.ts
  src/services/Api.ts
Labels: enhancement

#752 KIALI-1651 Add delete action on istio object page
  src/components/ListPage/ListPageLink.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigDetails/IstioRuleInfo.tsx
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/services/Api.ts
  src/types/IstioConfigDetails.ts
  src/types/IstioConfigList.ts
  src/types/Permissions.ts
Labels: PR Required

#770 KIALI-1792 Fix graph dropdown not updating namespace list
  src/components/NamespaceDropdown.tsx
  src/components/ToolbarDropdown/ToolbarDropdown.tsx
  src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
Labels: bug
