Repository kiali/kiali-ui, pull requests merged in 2019-04, with the labels that each got.

#1089 KIALI-2312 Add unlock icon to edges when mtls is enabled mesh-wide
  src/assets/img/graph-mtls-legend.svg
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/GraphFilter/GraphFind.tsx
  src/components/GraphFilter/GraphLegend.tsx
  src/components/GraphFilter/__tests__/GraphFind.test.tsx
  src/components/GraphFilter/__tests__/GraphLegend.test.tsx
  src/components/GraphFilter/__tests__/__snapshots__/GraphLegend.test.tsx.snap
  src/config/icons.ts
  src/containers/GraphPageContainer.ts
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/store/Selectors.ts
  src/store/Selectors/GraphData.ts
  src/types/Graph.ts
  src/types/TLSStatus.ts
Labels: PR Required :stop_sign:

#1029 Trivial: Filename changes to match our rules.
  src/actions/GraphDataThunkActions.ts
  src/actions/LoginThunkActions.ts
  src/app/AuthenticationController.tsx
  src/app/History.ts
  src/app/StartupInitializer.tsx
  src/components/DebugInformation/DebugInformation.tsx
  src/components/GraphFilter/GraphRefresh.tsx
  src/components/IstioWizards/IstioWizard.tsx
  src/components/IstioWizards/IstioWizardDropdown.tsx
  src/components/IstioWizards/Slider/Slider.tsx
  src/components/JaegerIntegration/__tests__/LookBack.test.tsx
  src/components/MetricsOptions/MetricsDuration.tsx
  src/components/Nav/UserDropdown.tsx
  src/components/SessionTimeout/SessionTimeout.tsx
  src/components/ToolbarDropdown/__tests__/ToolbarDropdown.test.tsx
  src/config/AuthenticationConfig.ts
  src/config/Config.ts
  src/config/Icons.ts
  src/config/JaegerQuery.ts
  src/config/Logos.ts
  src/config/ServerConfig.ts
  src/config/index.ts
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/Overview/OverviewToolbar.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/services/Login.ts
  src/services/Prometheus.ts
  src/utils/RateIntervals.ts
Labels: Refactor :recycle:

#1105 KIALI-2497 Show message to user at first load if secret is missing
  src/app/StartupInitializer.tsx
  src/config/AuthenticationConfig.ts
  src/pages/Login/LoginPage.tsx
  src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
  src/reducers/LoginState.ts
  src/types/Auth.ts
Labels: PR Required :stop_sign:

#1101 Kiali 577
  src/components/GraphFilter/GraphFilter.tsx
  src/config/Config.ts
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogsDraggable.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
  src/services/Api.ts
  src/services/__tests__/ApiMethods.test.tsx.ts
  src/types/IstioObjects.ts
Labels: PR Required :stop_sign:

#1092 KIALI-2625 [PF4] Move Initial adoption components
  package.json
  src/app/App.scss
  src/app/App.tsx
  src/app/AuthenticationController.tsx
  src/app/InitializingScreen.tsx
  src/components/About/AboutUIModal.tsx
  src/components/IstioWizards/MatchingRouting/RuleBuilder.tsx
  src/components/IstioWizards/Slider/Slider.tsx
  src/components/MTls/MeshMTLSStatus.tsx
  src/components/MessageCenter/MessageCenter.tsx
  src/components/MessageCenter/MessageCenterTrigger.tsx
  src/components/Nav/HelpDropdown.tsx
  src/components/Nav/Masthead/HelpDropdown.tsx
  src/components/Nav/Masthead/Masthead.tsx
  src/components/Nav/Masthead/UserDropdown.tsx
  src/components/Nav/Menu.tsx
  src/components/Nav/Navigation.tsx
  src/components/Nav/RenderPage.tsx
  src/components/Nav/SecondaryMasthead.tsx
  src/components/Nav/__tests__/Navigation.test.tsx
  src/components/Pf/PfContainerNavVertical.tsx
  src/config/Config.ts
  src/config/index.ts
  src/containers/HelpDropdownContainer.ts
  src/containers/NavigationContainer.ts
  src/containers/PfSpinnerContainer.tsx
  src/img/background-filter.svg
  src/img/pfbg_1200.jpg
  src/img/pfbg_2000.jpg
  src/img/pfbg_576.jpg
  src/img/pfbg_576@2x.jpg
  src/img/pfbg_768.jpg
  src/img/pfbg_768@2x.jpg
  src/img/pfbg_992.jpg
  src/index.css
  src/index.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/Login/__tests__/LoginPage.test.tsx
  src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
  src/pages/Overview/OverviewCardLinks.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.scss
  src/reducers/LoginState.ts
  src/styles/_layout.scss
  src/styles/_overrides.scss
  src/styles/index.scss
  src/types/Graph.ts
  yarn.lock
Labels: enhancement :rocket:, ux-review :pencil2:

#1116 KIALI-2712 Share duration with other tabs
  src/components/MetricsOptions/MetricsDuration.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
  src/services/Api.ts
Labels: PR Required :stop_sign:

#1117 KIALI-2724 Namespace Selector - Clear all does not uncheck pre-loaded…
  src/components/NamespaceDropdown.tsx
  src/styles/_overrides.scss
Labels: bug :bug:

#1111 KIALI-2454 Add service validations information to the UI
  src/pages/ServiceList/ItemDescription.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
  src/pages/ServiceList/__tests__/ItemDescription.test.tsx
  src/types/ServiceList.ts
Labels: Do NOT Merge (yet) :stop_sign:

#1125 KIALI-2732 [PF4] Upgrade patternfly/react-core to 3.2.6
  package.json
  src/styles/index.scss
  yarn.lock
Labels: Library Change :books:, Refactor :recycle:, enhancement :rocket:

#1137 KIALI-2764 Update typescript to 2.4.5 to get --incremental compile feature
  package.json
  tsconfig.json
  yarn.lock
Labels: Library Change :books:, enhancement :rocket:
