Repository kiali/kiali-ui, pull requests merged in 2019-07, with the labels that each got.

#1304 KIALI-3109 Fix service graph error
  src/pages/Graph/SummaryPanelNode.tsx
Labels: bug :bug:

#1303 KIALI-3093 Fix reset pagination when NS changes
  src/pages/AppList/AppListComponent.tsx
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
  src/pages/WorkloadList/WorkloadListComponent.tsx
  src/utils/Common.ts
Labels: backport_v1.0

#1299 Deps update: upgraded k-charted to get bug fix (KIALI-2985)
  package.json
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/Helper.ts
  src/components/Metrics/IstioMetrics.tsx
  src/components/Metrics/__tests__/CustomMetrics.test.tsx
  src/components/Metrics/__tests__/IstioMetrics.test.tsx
  src/components/MetricsOptions/MetricsRawAggregation.tsx
  src/components/MetricsOptions/MetricsSettings.tsx
  src/services/Api.ts
  src/types/Metrics.ts
  src/types/MetricsOptions.ts
  yarn.lock
Labels: PR Required :stop_sign:

#1310 KIALI-3113 Disable actions when service has not valid Workloads
  src/components/IstioWizards/IstioWizardDropdown.tsx
Labels: backport_v1.0

#1317 KIALI-3114 Refresh PfTitle when props change
  src/components/Pf/PfTitle.tsx
Labels: backport_v1.0

#1321 KIALI-3116 Workaround to avoid graphical glitch on nav collapse
  src/pages/Overview/OverviewPage.tsx
Labels: backport_v1.0

#1320 KIALI-3123 Disable Actions on Service for User without permissions
  src/components/IstioWizards/IstioWizardDropdown.tsx
Labels: backport_v1.0

#1325 KIALI-3135 Add more typesafety to node/edge data
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/pages/Graph/SummaryPanelEdge.tsx
  src/store/Selectors/GraphData.ts
  src/types/Graph.ts
  src/utils/TrafficRate.ts
Labels: Refactor :recycle:

#1328 KIALI-3022 Make graph legend more maintainable and vertical orientation
  src/assets/img/graph-legend.svg
  src/assets/img/graph-mtls-legend.svg
  src/assets/img/legend/app.svg
  src/assets/img/legend/edge-error.svg
  src/assets/img/legend/edge-idle.svg
  src/assets/img/legend/edge-normal.svg
  src/assets/img/legend/edge-tcp.svg
  src/assets/img/legend/edge-warn.svg
  src/assets/img/legend/external-namespace.svg
  src/assets/img/legend/mtls-badge.svg
  src/assets/img/legend/node-badge-circuit-breaker.svg
  src/assets/img/legend/node-badge-missing-sidecar.svg
  src/assets/img/legend/node-badge-virtual-services.svg
  src/assets/img/legend/node-color-error.svg
  src/assets/img/legend/node-color-normal.svg
  src/assets/img/legend/node-color-unused.svg
  src/assets/img/legend/node-color-warning.svg
  src/assets/img/legend/node.svg
  src/assets/img/legend/restricted-namespace.svg
  src/assets/img/legend/service-entry.svg
  src/assets/img/legend/service.svg
  src/assets/img/legend/traffic-failed-request.svg
  src/assets/img/legend/traffic-normal-request.svg
  src/assets/img/legend/traffic-tcp.svg
  src/assets/img/legend/unknown.svg
  src/components/GraphFilter/GraphLegend.tsx
  src/components/GraphFilter/GraphLegendData.ts
  src/components/GraphFilter/__tests__/__snapshots__/GraphLegend.test.tsx.snap
Labels: Refactor :recycle:, enhancement :rocket:

#1301 KIALI-3107 Typescript requirement warning by typescript-estree, typescript should be <3.5
  package.json
  yarn.lock
Labels: bug :bug:
