Repository kiali/kiali-ui, pull requests merged in 2019-06, with the labels that each got.

#1234 KIALI-2963 / KIALI-2966 simplify grafana model
  src/components/Metrics/IstioMetrics.tsx
  src/components/Metrics/__tests__/IstioMetrics.test.tsx
  src/reducers/GrafanaState.ts
  src/store/Store.ts
Labels: PR Required :stop_sign:

#1247 KIALI-2916 tracing screen - increase the font of service and lookback field names
  src/components/JaegerIntegration/JaegerToolbar.tsx
  src/components/JaegerIntegration/LookBack.tsx
  src/components/JaegerIntegration/ServiceDropdown.tsx
  src/components/JaegerIntegration/TagsControl.tsx
  src/components/JaegerIntegration/__tests__/__snapshots__/ServiceDropdown.test.tsx.snap
  src/components/JaegerIntegration/__tests__/__snapshots__/TagsControl.test.tsx.snap
  src/components/JaegerIntegration/_jaegerIntegration.scss
  src/styles/index.scss
Labels: ux-review :pencil2:

#1255 KIALI-3002 Fix Handlebars subpackages CVE with version < 4.0.14.
  package.json
  yarn.lock
Labels: Library Change :books:

#1254 KIALI-3001 Makes graph labels selectable
  package.json
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  yarn.lock
Labels: Library Change :books:

#1239 KIALI-2529 Fix values that can be undefined or null
  src/actions/GraphActions.ts
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/FocusAnimation.ts
  src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
  src/components/GraphFilter/GraphFind.tsx
  src/components/Metrics/IstioMetrics.tsx
  src/components/MetricsOptions/MetricsSettings.tsx
  src/components/Nav/Masthead/UserDropdown.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/ServiceDetails/ServiceInfo/types/DestinationRuleValidator.ts
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/reducers/__tests__/NamespacesReducer.test.ts
  src/store/Store.ts
Labels: DNM / post-ga :stop_sign:

#1261 KIALI-3028 Allow DestinationRules without subset.labels
  src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
Labels: backport_v0.21

#1267 KIALI-3031 Add missing fields in VS/SE
  src/types/IstioObjects.ts
Labels: PR Required :stop_sign:, backport_v1.0

#1268 KIALI-3048 Fix vertical scroll appearing in workload logs tab
  src/styles/_layout.scss
Labels: backport_v1.0

#1144 KIALI-2579 Use k-charted and remove Dashboards code
  package.json
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/Dashboard.tsx
  src/components/Metrics/Helper.ts
  src/components/Metrics/HistogramChart.tsx
  src/components/Metrics/IstioMetrics.tsx
  src/components/Metrics/MetricChart.tsx
  src/components/Metrics/MetricsChartBase.tsx
  src/components/Metrics/__tests__/CustomMetrics.test.tsx
  src/components/Metrics/__tests__/IstioMetrics.test.tsx
  src/components/MetricsOptions/MetricsRawAggregation.tsx
  src/components/MetricsOptions/MetricsSettings.tsx
  src/config/Config.ts
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Overview/OverviewPage.tsx
  src/services/Api.ts
  src/services/__tests__/ApiMethods.test.tsx.ts
  src/types/Metrics.ts
  src/types/MetricsOptions.ts
  src/utils/Graphing.ts
  yarn.lock
Labels: PR Required :stop_sign:

#1262 KIALI-2976 Check jaeger access after Authentication
  src/actions/ActionKeys.ts
  src/actions/JaegerActions.ts
  src/app/AuthenticationController.tsx
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/JaegerIntegration/JaegerIntegration.tsx
  src/components/Nav/Navigation.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/reducers/JaegerState.ts
  src/reducers/__tests__/JaegerStateReducer.test.ts
  src/store/Store.ts
Labels: PR Required :stop_sign:, backport_v1.0

#1281 KIALI-3055 Fix namespace scrollbar for non-webkit browsers
  src/components/NamespaceDropdown.tsx
Labels: backport_v1.0

#1280 Prepare for major release workflow
  Makefile.jenkins
  RELEASING.adoc
Labels: backport_v1.0

#1271 KIALI-3034 Improve side-panel for serviceEntry nodes
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/config/Paths.ts
  src/pages/Graph/SummaryLink.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelNode.tsx
Labels: PR Required :stop_sign:

#1284 KIALI-3057 mTLS status messages reduced to informative when user hasn't namespaces
  src/app/AuthenticationController.tsx
  src/components/MTls/MeshMTLSStatus.tsx
  src/services/Api.ts
Labels: PR Required :stop_sign:

#1286 KIALI-3034 Improve side-panel for serviceEntry nodes (#1271)
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/config/Paths.ts
  src/pages/Graph/SummaryLink.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelNode.tsx
Labels: PR Required :stop_sign:, backport_v1.0

#1285 KIALI-3065 reset state of jaeger/grafana info on error
  src/app/AuthenticationController.tsx
Labels: backport_v1.0

#1287 KIALI-3071 Split details and 3scale promises
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
Labels: backport_v1.0
