Repository kiali/kiali-ui, pull requests merged in 2019-03, with the labels that each got.

#1031 KIALI-2442 Map kind and apiVersion attributes
  src/types/IstioObjects.ts
Labels: PR Required :stop_sign:

#984 KIALI-2361 Make graph side panel collapsible
  src/components/SummaryPanel/InOutRateChart.tsx
  src/components/SummaryPanel/RateChart.tsx
  src/components/SummaryPanel/ResponseTimeChart.tsx
  src/components/SummaryPanel/RpsChart.tsx
  src/components/Tour/Tour.tsx
  src/pages/Graph/GraphHelpTour.ts
  src/pages/Graph/SummaryPanel.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/types/Graph.ts
Labels: ux-review :pencil2:

#1028 KIALI-2380 Session handling using cookies
  public/index.html
  src/actions/GrafanaThunkActions.ts
  src/actions/GraphDataThunkActions.ts
  src/actions/JaegerThunkActions.ts
  src/actions/LoginThunkActions.ts
  src/actions/NamespaceThunkActions.ts
  src/actions/__tests__/LoginAction.test.ts
  src/actions/__tests__/NamespaceAction.test.ts
  src/app/App.scss
  src/app/App.tsx
  src/app/AppConfigs.ts
  src/app/InitializingScreen.tsx
  src/app/StartupInitializer.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/Filters/NamespaceFilter.ts
  src/components/IstioWizards/IstioWizard.tsx
  src/components/IstioWizards/IstioWizardDropdown.tsx
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/IstioMetrics.tsx
  src/components/Nav/Navigation.tsx
  src/components/Nav/UserDropdown.tsx
  src/config/config.ts
  src/containers/UserDropdownContainer.ts
  src/helpers/TrafficDetailsHelper.ts
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/AppList/AppListClass.tsx
  src/pages/AppList/AppListComponent.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/Login/LoginPage.tsx
  src/pages/Overview/OverviewPage.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadList/WorkloadListComponent.tsx
  src/services/Api.ts
  src/services/Login.ts
  src/services/__tests__/ApiMethods.test.tsx.ts
  src/store/ConfigStore.ts
  src/store/Store.ts
  src/types/Auth.ts
  src/types/Common.ts
  src/types/Redux.ts
  src/utils/Authentication.ts
  src/utils/AuthenticationToken.ts
  src/utils/__tests__/Authentication.test.ts
Labels: PR Required :stop_sign:

#1051 Add Documentation to the style guide for type-safe Redux
  STYLE_GUIDE.adoc
Labels: Documentation :memo:

#1054 KIALI-2273 Fix SessionTimeout dialog
  src/actions/LoginActions.ts
  src/actions/LoginThunkActions.ts
  src/app/App.tsx
  src/components/Nav/UserDropdown.tsx
  src/components/SessionTimeout/SessionTimeout.tsx
  src/config/config.ts
  src/containers/UserDropdownContainer.ts
  src/pages/Login/LoginPage.tsx
  src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
  src/reducers/LoginState.ts
  src/reducers/MessageCenter.ts
  src/services/Api.ts
  src/store/Store.ts
Labels: PR Required :stop_sign:

#1060 KIALI-2429 Show namespace-wide mTLS in the overview card
  src/assets/img/mtls-status-full-dark.svg
  src/assets/img/mtls-status-partial-dark.svg
  src/components/IstioWizards/IstioWizard.tsx
  src/components/IstioWizards/IstioWizardDropdown.tsx
  src/components/IstioWizards/TrafficPolicy.tsx
  src/components/MTls/MTLSIcon.tsx
  src/components/MTls/MTLSStatus.tsx
  src/components/MTls/MeshMTLSStatus.tsx
  src/components/MTls/NamespaceMTLSStatus.tsx
  src/components/MTls/__tests__/MTLSIcon.test.tsx
  src/components/MTls/__tests__/__snapshots__/MTLSIcon.test.tsx.snap
  src/components/Nav/MeshMTLSStatus.tsx
  src/components/Nav/Navigation.tsx
  src/config/config.ts
  src/containers/GlobalMTLSContainer.ts
  src/containers/TrafficPolicyContainer.tsx
  src/pages/Overview/NamespaceInfo.ts
  src/pages/Overview/OverviewPage.tsx
  src/pages/Overview/OverviewStatuses.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/services/Api.ts
  src/store/Selectors.ts
  src/types/ServiceInfo.ts
  src/types/TLSStatus.ts
Labels: PR Required :stop_sign:

#1062 KIALI-470 Add Response Code summary to Edge side panel
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/components/SummaryPanel/ResponseTable.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/store/Selectors/GraphData.ts
  src/types/Graph.ts
Labels: PR Required :stop_sign:

#1082 Kiali-907: Error messages pile up infinitely.
  src/components/MessageCenter/NotificationDrawer.tsx
  src/components/MessageCenter/__tests__/MessageCenter.test.tsx
  src/reducers/MessageCenter.ts
  src/reducers/__tests__/MessageCenterReducer.test.ts
  src/types/MessageCenter.ts
Labels: enhancement :rocket:

#1084 Kiali-2586 Update many of the libs except for React.js related.
  package.json
  yarn.lock
Labels: Do NOT Merge (yet) :stop_sign:
