Repository kiali/kiali-ui, pull requests merged in 2019-08, with the labels that each got.

#1353 KIALI-2938 MessageCenter improvements and detail handling
  src/actions/GraphDataThunkActions.ts
  src/actions/LoginThunkActions.ts
  src/actions/MessageCenterActions.ts
  src/actions/__tests__/MessageCenterAction.test.ts
  src/app/AuthenticationController.tsx
  src/app/StartupInitializer.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/IstioWizards/IstioWizard.tsx
  src/components/IstioWizards/IstioWizardDropdown.tsx
  src/components/IstioWizards/ThreeScaleIntegration.tsx
  src/components/ListPage/ListComponent.tsx
  src/components/MTls/MeshMTLSStatus.tsx
  src/components/MessageCenter/NotificationDrawer.tsx
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/IstioMetrics.tsx
  src/helpers/TrafficDetailsHelper.ts
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/Overview/OverviewPage.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/reducers/MessageCenter.ts
  src/reducers/__tests__/MessageCenterReducer.test.ts
  src/services/Api.ts
  src/services/__tests__/ApiMethods.test.tsx.ts
  src/types/MessageCenter.ts
  src/utils/MessageCenter.ts
Labels: PR Required :stop_sign:

#1357 KIALI-3193 Add support for ServiceMeshPolicy,ServiceMeshRbacConfig
  src/components/VirtualList/Config.ts
  src/pages/IstioConfigList/FiltersAndSorts.ts
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/types/IstioConfigDetails.ts
  src/types/IstioConfigList.ts
  src/types/IstioObjects.ts
  src/utils/IstioConfigUtils.ts
Labels: Do NOT Merge (yet) :stop_sign:, PR Required :stop_sign:, backport_v1.0

#1335 issue 1053 - LDAP integration - changes to kiali-ui
  src/pages/Login/LoginPage.tsx
  src/services/Login.ts
  src/types/Auth.ts
Labels: PR Required :stop_sign:, enhancement :rocket:

#1361 KIALI-3195 UI-side changes for multi-namespace Istio deployment
  src/actions/GraphDataThunkActions.ts
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/MissingSidecar/MissingSidecar.tsx
  src/components/VirtualList/Config.ts
  src/config/ServerConfig.ts
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/SummaryLink.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/store/Selectors/GraphData.ts
  src/types/Graph.ts
  src/types/ServerConfig.ts
Labels: PR Required :stop_sign:
