Repository kiali/kiali-ui, pull requests merged in 2019-01, with the labels that each got.

#908 KIALI-2204 - Upgrades patternfly version
  package.json
  yarn.lock
Labels: Library Change :books:

#864 KIALI-2077 React related libraries upgrades
  package.json
  src/actions/LoginThunkActions.ts
  src/app/History.ts
  src/components/Details/__tests__/__snapshots__/DetailObject.test.tsx.snap
  src/components/GraphFilter/__tests__/__snapshots__/GraphLegend.test.tsx.snap
  src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/components/Label/__tests__/__snapshots__/Label.test.tsx.snap
  src/components/Metrics/__tests__/__snapshots__/Metrics.test.tsx.snap
  src/components/MetricsOptions/__tests__/__snapshots__/MetricsOptionsBar.test.tsx.snap
  src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
  src/config/config.ts
  src/config/index.ts
  src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
  src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoCard.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoPods.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/pages/ServiceList/__tests__/__snapshots__/RateIntervalToolbarItem.test.tsx.snap
  src/services/Api.ts
  yarn.lock
Labels: Do NOT Merge (yet) :stop_sign:, Library Change :books:

#892 KIALI-1671 Refactor validation endpoints
  src/components/ConfigValidation/ConfigIndicator.tsx
  src/config/Config.ts
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/DestinationRuleDetail.tsx
  src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/VirtualServiceDetail.tsx
  src/pages/ServiceDetails/ServiceInfo/IstioObjectDetails/VirtualServiceRoute.tsx
  src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/services/Api.ts
  src/services/__mockData__/getIstioConfigBookinfo.json
  src/services/__mockData__/getIstioConfigDetail.json
  src/services/__mockData__/getIstioConfigValidations.json
  src/services/__mockData__/getNamespaceValidations.json
  src/services/__mockData__/getServiceDetail.json
  src/services/__mockData__/getServiceValidations.json
  src/services/__mocks__/Api.ts
  src/services/__tests__/Api.test.tsx
  src/services/__tests__/ApiMethods.test.tsx.ts
  src/types/AceValidations.ts
  src/types/IstioConfigDetails.ts
  src/types/IstioConfigList.ts
  src/types/IstioObjects.ts
  src/types/ServiceInfo.ts
  src/types/__tests__/AceValidations.test.ts
Labels: PR Required :stop_sign:

#932 KIALI-2237 Rename chart model counterRate -> metric
  src/components/Metrics/Dashboard.tsx
  src/components/Metrics/Helper.ts
  src/components/Metrics/__tests__/IstioMetrics.test.tsx
  src/types/Metrics.ts
Labels: PR Required :stop_sign:

#953 KIALI-2071 Allow the user to copy debug information
  package.json
  src/actions/GraphDataActions.ts
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/DebugInformation/DebugInformation.tsx
  src/components/Nav/HelpDropdown.tsx
  src/containers/DebugInformationContainer.tsx
  src/containers/GraphPageContainer.ts
  src/store/Selectors.ts
  src/store/Selectors/GraphData.ts
  yarn.lock
Labels: Library Change :books:

#948 KIALI-2269 Update runtimes model to dissociate with dashboards
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/types/App.ts
  src/types/Workload.ts
Labels: PR Required :stop_sign:

#949 KIALI-2256 Wizard for creating traffic rules
  src/components/IstioWizards/IstioWizard.tsx
  src/components/IstioWizards/IstioWizardDropdown.tsx
  src/components/IstioWizards/Slider/BootstrapSlider.tsx
  src/components/IstioWizards/Slider/Boundaries.tsx
  src/components/IstioWizards/Slider/DropdownMenu.tsx
  src/components/IstioWizards/Slider/Slider.tsx
  src/config/Config.ts
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/services/Api.ts
  src/types/IstioConfigList.ts
  src/types/IstioObjects.ts
  src/types/Permissions.ts
Labels: Do NOT Merge (yet) :stop_sign:

#961 KIALI-2300 KIALI-2304 Links from Overview page are not filtering by namespace
  src/components/Filters/NamespaceFilter.ts
  src/components/ListPage/ListPageLink.tsx
  src/config/Paths.ts
  src/config/index.ts
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/Overview/OverviewPage.tsx
  src/pages/Overview/OverviewStatus.tsx
  src/pages/Overview/OverviewStatuses.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/routes.tsx
Labels: bug :bug:

#966 Add patternfly-react-extensions library
  package.json
  src/app/App.scss
  yarn.lock
Labels: Library Change :books:

#959 KIALI-2069 Persist selected namespace
  package.json
  src/store/ConfigStore.ts
  yarn.lock
Labels: Library Change :books:
