Repository kiali/kiali-ui, pull requests merged in 2019-10, with the labels that each got.

#1456 Health and validations icon colors now are down to 100
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/components/Pf/PfColors.tsx
Labels: team/saturn

#1430 UI-side support for request.host information
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/components/SummaryPanel/ResponseFlagsTable.tsx
  src/components/SummaryPanel/ResponseHostsTable.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/types/Graph.ts
Labels: backend changes required, team/saturn

#1461 Fix Find/Hide not working for =, != numeric expressions
  src/components/GraphFilter/GraphFind.tsx
  src/components/GraphFilter/__tests__/GraphFind.test.tsx
  src/pages/Graph/GraphHelpFind.tsx
Labels: team/saturn

#1385 Implement UXD changes for the graph
  package.json
  src/assets/img/legend/edge-error.svg
  src/assets/img/legend/edge-idle.svg
  src/assets/img/legend/edge-normal.svg
  src/assets/img/legend/edge-warn.svg
  src/assets/img/legend/node-badge-circuit-breaker.svg
  src/assets/img/legend/node-badge-missing-sidecar.svg
  src/assets/img/legend/node-badge-virtual-services.svg
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
  src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/Pf/PfColors.tsx
  src/config/Icons.ts
  yarn.lock
Labels: do not merge, library change, team/saturn

#1460 Fix issue when hide expression hides app box elements
  src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts
Labels: team/saturn

#1459 Display Service Entries in traffic tab
  src/components/Details/DetailedTrafficList.tsx
  src/components/Details/__tests__/DetailedTrafficList.test.tsx
  src/components/Metrics/TrafficDetails.tsx
  src/components/Metrics/__tests__/TrafficDetails.test.tsx
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Labels: team/saturn

#1464 Tweak to the group compound layout algorithm
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts
Labels: team/saturn

#1463 Updates node shapes in the legend
  src/assets/img/legend/app.svg
  src/assets/img/legend/service-entry.svg
  src/assets/img/legend/service.svg
  src/assets/img/legend/unknown.svg
Labels: team/saturn

#1466 Do not rely on "startBatch" for locking positions
  src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts
Labels: refactor, team/saturn

#1469 Reset to node's positions and small tweaks
  src/components/CytoscapeGraph/Layout/GroupCompoundLayout.ts
  src/components/GraphFilter/GraphFind.tsx
Labels: team/saturn

#1455 Migrate DebugInformation modal to PF4
  src/components/DebugInformation/DebugInformation.tsx
  src/styles/_overrides.scss
Labels: team/jupiter

#1470 Fix Kiosk mode not working
  src/styles/_overrides.scss
Labels: team/jupiter, team/saturn

#1458 PF4 the GraphSettings display menu.
  src/components/GraphFilter/GraphSettings.tsx
Labels: team/saturn

#1484 List views alignment issue
  package.json
  src/components/MissingSidecar/MissingSidecar.tsx
  src/components/VirtualList/Renderers.tsx
  src/components/VirtualList/VirtualTable.tsx
  src/pages/AppDetails/AppInfo/AppDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx
Labels: team/saturn

#1496 Create Pf4Icon function to consolidate all of the icons into a single place
  src/config/KialiIcon.tsx
  src/pages/Graph/SummaryPanelNode.tsx
Labels: refactor, team/saturn

#1492 Bump versions of PF4 libs and migrate to Red Hat fonts
  package.json
  public/index.html
  src/components/Details/DetailedTrafficList.tsx
  src/components/GraphFilter/GraphSettings.tsx
  src/components/GraphFilter/__tests__/__snapshots__/GraphLegend.test.tsx.snap
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/components/IstioWizards/MatchingRouting/Rules.tsx
  src/components/IstioWizards/SuspendTraffic.tsx
  src/components/IstioWizards/WeightedRouting.tsx
  src/components/JaegerIntegration/__tests__/__snapshots__/RightToolbar.test.tsx.snap
  src/components/JaegerIntegration/__tests__/__snapshots__/TagsControl.test.tsx.snap
  src/components/MTls/__tests__/__snapshots__/MTLSIcon.test.tsx.snap
  src/components/MetricsOptions/MetricsSettingsDropdown.tsx
  src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
  src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadServices.tsx
  src/styles/_overrides.scss
  src/styles/index.scss
  yarn.lock
Labels: library change, team/saturn

#1499 Trivial: Add additional icons to KialiIcon.tsx and make width of icons 10px.
  src/config/KialiIcon.tsx
Labels: refactor, team/saturn

#1502 ServiceDetailsPage: minor fixes
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
Labels: team/jupiter

#1505 PF4 Message Center
  src/actions/GraphDataThunkActions.ts
  src/actions/LoginThunkActions.ts
  src/app/AuthenticationController.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/FilterList/FilterHelper.ts
  src/components/GraphFilter/GraphFind.tsx
  src/components/IstioWizards/IstioWizard.tsx
  src/components/IstioWizards/IstioWizardDropdown.tsx
  src/components/IstioWizards/ThreeScaleIntegration.tsx
  src/components/MTls/MeshMTLSStatus.tsx
  src/components/MessageCenter/AlertDrawer.tsx
  src/components/MessageCenter/AlertDrawerGroup.tsx
  src/components/MessageCenter/AlertDrawerMessage.tsx
  src/components/MessageCenter/AlertToast.tsx
  src/components/MessageCenter/MessageCenter.tsx
  src/components/MessageCenter/MessageCenterTrigger.tsx
  src/components/MessageCenter/NotificationDrawer.tsx
  src/components/MessageCenter/NotificationList.tsx
  src/components/MessageCenter/__tests__/MessageCenter.test.tsx
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/IstioMetrics.tsx
  src/config/KialiIcon.tsx
  src/helpers/TrafficDetailsHelper.ts
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/types/MessageCenter.ts
  src/utils/AlertUtils.ts
  src/utils/IstioValidationUtils.ts
Labels: team/saturn

#1510 Code cleanup
  src/components/Filters/NamespaceFilter.ts
  src/components/Filters/StatefulFilters.tsx
  src/components/Pf/PfAlerts.tsx
  src/components/Pf/PfContainerNavVertical.tsx
  src/components/Pf/PfHeader.tsx
  src/components/UpstreamDetector/UpstreamDetector.tsx
  src/store/Selectors.ts
  src/types/Common.ts
  src/types/Graph.ts
  src/types/IstioConfigList.ts
  src/types/IstioObjects.ts
  src/types/NamespaceId.ts
  src/types/ServiceInfo.ts
  src/types/Workload.ts
  src/utils/RateIntervals.ts
Labels: team/saturn

#1507 Appliations Health to the same style as Service and Workload.
  src/pages/AppDetails/AppInfo/AppDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
Labels: team/jupiter

#1509 Use mountOnEnter and unmountOnExit for PF Tabs
  src/components/Tab/Tabs.tsx
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Labels: refactor, team/saturn

#1506 [PF4] Replace PF3 icons with PF4 icons via KialiIcon.tsx.
  src/components/About/AboutUIModal.tsx
  src/components/GraphFilter/GraphFind.tsx
  src/components/NamespaceDropdown.tsx
  src/components/Tour/Tour.tsx
  src/config/KialiIcon.tsx
  src/pages/Graph/GraphHelpFind.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/SummaryLink.tsx
  src/pages/Graph/SummaryPanel.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNode.tsx
Labels: refactor, team/saturn

#1514 Use Select control in graph's Display dropdown
  src/components/GraphFilter/GraphSettings.tsx
Labels: refactor, team/saturn
