Repository kiali/kiali-ui, pull requests merged in 2019-12, with the labels that each got.

#1572 Implement token authentication
  src/pages/Login/LoginPage.tsx
  src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
  src/services/Api.ts
  src/services/Login.ts
  src/services/__tests__/ApiMethods.test.tsx.ts
  src/types/Auth.ts
Labels: backend changes required, team/saturn

#1573 Make the cytoscape bottom toolbar more readable
  src/components/CytoscapeGraph/CytoscapeToolbar.tsx
Labels: team/saturn

#1574 Update Wizards to use FQDN
  src/components/IstioWizards/IstioWizard.tsx
  src/components/IstioWizards/IstioWizardActions.ts
  src/config/ServerConfig.ts
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
  src/types/ServerConfig.ts
Labels: team/jupiter

#1580 Remove link redundancy in cards of Overview page
  src/pages/Overview/OverviewCardLinks.tsx
  src/pages/Overview/__tests__/OverviewCardLinks.test.tsx
Labels: team/saturn

#1560 Traces (spans) in metrics
  package.json
  src/components/Metrics/IstioMetrics.tsx
  src/config/Config.ts
  src/services/Api.ts
  src/types/Tracing.ts
  yarn.lock
Labels: team/jupiter

#1579 Update Patternfly4
  package.json
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/components/JaegerIntegration/__tests__/__snapshots__/ServiceDropdown.test.tsx.snap
  src/components/JaegerIntegration/__tests__/__snapshots__/TagsControl.test.tsx.snap
  src/components/MTls/__tests__/__snapshots__/MTLSIcon.test.tsx.snap
  src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
  src/pages/Graph/GraphToolbar/__tests__/__snapshots__/GraphLegend.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  yarn.lock
Labels: library change

#1584 Update react-scripts from 3.2.0 to 3.3.0 to fix Snyk vulnerability
  package.json
  yarn.lock
Labels: library change, team/saturn

#1582 Add Support to AuthorizationPolicies CRD
  src/components/VirtualList/Config.ts
  src/pages/IstioConfigList/FiltersAndSorts.ts
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/types/IstioConfigDetails.ts
  src/types/IstioConfigList.ts
  src/types/IstioObjects.ts
  src/utils/IstioConfigUtils.ts
Labels: backend changes required

#1586 Link from overview page, service page and istio config to validation page
  src/components/VirtualList/Renderers.tsx
  src/pages/Overview/OverviewPage.tsx
Labels: team/jupiter

#1587 show the new container version in the about box
  src/components/About/AboutUIModal.tsx
  src/types/StatusState.ts
Labels: backend changes required, team/saturn

#1583 Make Graph Settings display settings more consistent
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
Labels: refactor, team/saturn
