Repository kiali/kiali-ui, pull requests merged in 2019-11, with the labels that each got.

#1515 PF4 Help Tours
  src/actions/ActionKeys.ts
  src/actions/KialiAppAction.ts
  src/actions/TourActions.ts
  src/components/CytoscapeGraph/CytoscapeToolbar.tsx
  src/components/GraphFilter/GraphFilter.tsx
  src/components/GraphFilter/GraphFind.tsx
  src/components/MessageCenter/NotificationList.tsx
  src/components/NamespaceDropdown.tsx
  src/components/Tour/StatefulTour.tsx
  src/components/Tour/Tour.tsx
  src/components/Tour/TourStop.tsx
  src/config/KialiIcon.tsx
  src/pages/Graph/GraphHelpTour.ts
  src/pages/Graph/GraphPage.tsx
  src/reducers/TourState.ts
  src/reducers/index.ts
  src/store/ConfigStore.ts
  src/store/Store.ts
Labels: team/saturn

#1519 PF4 Graph Find/Hide, including Help
  package.json
  src/components/GraphFilter/GraphFind.tsx
  src/components/Tab/SimpleTabs.tsx
  src/pages/Graph/GraphHelpFind.tsx
  yarn.lock
Labels: team/saturn

#1526 graph UX - solid edges, updated legend, larger animation particles
  src/assets/img/legend/edge-danger.svg
  src/assets/img/legend/edge-idle.svg
  src/assets/img/legend/edge-success.svg
  src/assets/img/legend/edge-warn.svg
  src/components/CytoscapeGraph/TrafficAnimation/TrafficPointRenderer.ts
  src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
Labels: team/saturn

#1523 Pf4 the namespace selector
  src/components/NamespaceDropdown.tsx
Labels: team/saturn

#1525 Remove PF3 notifications from ServiceInfo
  src/components/MessageCenter/AlertToast.tsx
  src/components/MessageCenter/NotificationList.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
Labels: team/saturn

#1530 Change the background from gray to white on the Metrics Settings dropdown
  src/components/MetricsOptions/MetricsSettingsDropdown.tsx
Labels: team/saturn

#1524 Support MUTUAL Tls method in Wizard with extended form
  src/components/IstioWizards/IstioWizard.tsx
  src/components/IstioWizards/IstioWizardActions.ts
  src/components/IstioWizards/TrafficPolicy.tsx
  src/types/IstioObjects.ts
Labels: team/jupiter

#1535 Fix regression, ensure NamespaceDropdown refreshes accessible namespaces
  src/components/NamespaceDropdown.tsx
Labels: team/saturn

#1529 Patternfly-fourize EmptyGraph control
  src/components/EmptyGraphLayout.tsx
Labels: team/saturn

#1516 Fix BrowsersList warning and other package.json updates
  deps-and-resolutions-notes.txt
  package.json
  yarn.lock
Labels: team/saturn

#1431 KIALI-1600 [PF4] Create background in grey color as suggested by UX for all views
  src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
  src/components/JaegerIntegration/JaegerIntegration.tsx
  src/components/Metrics/IstioMetrics.tsx
  src/components/Metrics/TrafficDetails.tsx
  src/components/Metrics/__tests__/IstioMetrics.test.tsx
  src/components/Nav/Page/RenderContent.tsx
  src/components/Nav/Page/RenderHeader.tsx
  src/components/Nav/Page/index.ts
  src/components/Nav/RenderPage.tsx
  src/components/Nav/SecondaryMasthead.tsx
  src/components/VirtualList/VirtualList.tsx
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/AppList/AppListPage.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigList/IstioConfigListPage.tsx
  src/pages/Overview/OverviewPage.tsx
  src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceTraces.tsx
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/pages/ServiceList/ServiceListPage.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
  src/pages/WorkloadList/WorkloadListPage.tsx
  src/styles/_layout.scss
Labels: team/jupiter, ux review required

#1539 Move refresher button to UX design
  src/components/Refresh/RefreshButton.tsx
Labels: team/jupiter

#1537 Pf4 the GraphFilter.tsx
  src/components/GraphFilter/GraphFilter.tsx
Labels: team/saturn

#1538 Patternfly-fourize graph page
  src/pages/Graph/GraphPage.tsx
Labels: team/saturn

#1527 Show additional configured details (annotations)
  src/components/TextOrLink.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoDescription.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceMock.ts
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/WorkloadDescription.test.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
  src/services/__mockData__/getServiceDetail.ts
  src/types/ServiceInfo.ts
  src/types/Workload.ts
Labels: backend changes required

#1522 Add referenced istio objects to validations
  src/components/Link/IstioObjectLink.tsx
  src/components/VirtualList/Config.ts
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/types/IstioObjects.ts
Labels: backend changes required

#1540 Fix double scroll and fix last row in lists
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/IstioMetrics.tsx
  src/components/Metrics/TrafficDetails.tsx
  src/components/Nav/Navigation.tsx
  src/components/Nav/Page/RenderComponentScroll.tsx
  src/components/Nav/Page/RenderContent.tsx
  src/components/Nav/Page/index.ts
  src/components/Nav/RenderPage.tsx
  src/components/VirtualList/VirtualTable.tsx
  src/pages/AppDetails/AppInfo.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceTraces.tsx
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
  src/styles/_layout.scss
Labels: team/jupiter

#1542 Use PF4 css color variables more consistently
  src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/Health/__tests__/HealthIndicator.test.tsx
  src/components/Pf/PfColors.tsx
  src/components/SessionTimeout/SessionTimeout.tsx
  src/components/SummaryPanel/RateChart.tsx
  src/components/SummaryPanel/RpsChart.tsx
  src/components/Validations/Validation.tsx
  src/config/KialiIcon.tsx
  src/types/Health.ts
Labels: team/saturn

#1543 Unmount non visibible children instead to mountonenter only
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Labels: team/jupiter

#1486 Add Jaeger configuration for namespaceSelector
  src/app/AuthenticationController.tsx
  src/app/History.ts
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/JaegerIntegration/JaegerIntegration.tsx
  src/components/JaegerIntegration/JaegerToolbar.tsx
  src/components/JaegerIntegration/RouteHelper.ts
  src/components/JaegerIntegration/ServiceDropdown.tsx
  src/components/JaegerIntegration/__tests__/JaegerToolbar.test.tsx
  src/reducers/JaegerState.ts
  src/reducers/__tests__/JaegerStateReducer.test.ts
  src/store/Store.ts
  src/types/JaegerInfo.ts
Labels: team/jupiter

#1548 Fix Logs page, message error not centered
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
Labels: team/jupiter

#1545 Improve handling when graph summary target element changes
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNode.tsx
Labels: team/saturn

#1547 Fix Overview Page, message not centered
  src/pages/Overview/OverviewPage.tsx
  src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
Labels: team/jupiter

#1473 [Pf4] MIgrate the Graph Side Panel
  src/components/SummaryPanel/ResponseFlagsTable.tsx
  src/components/SummaryPanel/ResponseHostsTable.tsx
  src/components/Tab/SimpleTabs.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNode.tsx
Labels: team/saturn

#1544 3scale fixes
  src/components/IstioWizards/IstioWizard.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
Labels: team/jupiter

#1546 Adjust size of subsets column in DR table
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
Labels: team/jupiter

#1541 Adding validation status to Overview page
  src/components/Validations/Validation.tsx
  src/components/Validations/ValidationObjectSummary.tsx
  src/components/Validations/ValidationSummary.tsx
  src/components/VirtualList/Renderers.tsx
  src/config/Config.ts
  src/pages/Overview/NamespaceInfo.ts
  src/pages/Overview/OverviewPage.tsx
  src/pages/Overview/Sorts.ts
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
  src/services/Api.ts
  src/types/IstioObjects.ts
Labels: backend changes required, team/jupiter

#1553 remove null markers
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNode.tsx
Labels: team/saturn

#1565 Fix regression: properly set lastRefreshAt
  src/components/Refresh/Refresh.tsx
Labels: team/saturn

#1564 Straight re-factor of code for better consistency
  src/actions/ActionKeys.ts
  src/actions/GraphActions.ts
  src/actions/GraphDataThunkActions.ts
  src/actions/GraphFilterActions.ts
  src/actions/GraphToolbarActions.ts
  src/actions/KialiAppAction.ts
  src/actions/__tests__/GraphFilterAction.test.tsx
  src/actions/__tests__/GraphToolbarAction.test.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/components/CytoscapeGraph/CytoscapeToolbar.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/CytoscapeGraph/graphs/LayoutDictionary.ts
  src/components/EmptyGraphLayout.tsx
  src/components/Nav/NavUtils.tsx
  src/pages/Graph/GraphLegend.tsx
  src/pages/Graph/GraphLegendData.ts
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx
  src/pages/Graph/GraphToolbar/__tests__/GraphLegend.test.tsx
  src/pages/Graph/GraphToolbar/__tests__/__snapshots__/GraphLegend.test.tsx.snap
  src/reducers/GraphDataState.ts
  src/reducers/__tests__/GraphDataState.test.ts
  src/store/Selectors.ts
  src/store/Store.ts
  src/types/Graph.ts
  src/types/GraphFilter.ts
Labels: team/saturn

#1567 Add support for Node.js 12 LTS
  .travis.yml
  package.json
  src/pages/Overview/__tests__/OverviewPage.test.tsx
  yarn.lock
Labels: library change, team/saturn

#1562 Introduce 'is present' syntax sugar for Matching Routing
  src/components/IstioWizards/MatchingRouting.tsx
  src/components/IstioWizards/MatchingRouting/MatchBuilder.tsx
Labels: team/jupiter

#1570 Reset state when Wizard is closed
  src/components/IstioWizards/IstioWizard.tsx
Labels: team/jupiter
