Repository kiali/kiali-ui, pull requests merged in 2019-05, with the labels that each got.

#1134 KIALI-2676 Show ExternalName field for ExternalName Services
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/services/__mockData__/getServiceDetail.ts
  src/types/ServiceInfo.ts
Labels: PR Required :stop_sign:

#1164 KIALI-2627 [PF4] Jaeger Integration with Kiali
  src/components/JaegerIntegration/JaegerToolbar.tsx
  src/components/JaegerIntegration/LookBack.tsx
  src/components/JaegerIntegration/RightToolbar.tsx
  src/components/JaegerIntegration/ServiceDropdown.tsx
  src/components/JaegerIntegration/TagsControl.tsx
  src/components/JaegerIntegration/__tests__/LookBack.test.tsx
  src/components/JaegerIntegration/__tests__/RightToolbar.test.tsx
  src/components/JaegerIntegration/__tests__/ServiceDropdown.test.tsx
  src/components/JaegerIntegration/__tests__/TagsControl.test.tsx
  src/components/JaegerIntegration/__tests__/__snapshots__/RightToolbar.test.tsx.snap
  src/components/JaegerIntegration/__tests__/__snapshots__/ServiceDropdown.test.tsx.snap
  src/components/JaegerIntegration/__tests__/__snapshots__/TagsControl.test.tsx.snap
  src/components/Nav/Navigation.tsx
Labels: Refactor :recycle:, enhancement :rocket:

#1162 KIALI-2641 Add Wizard for 3scale adapter config
  src/components/IstioWizards/IstioWizard.tsx
  src/components/IstioWizards/IstioWizardActions.ts
  src/components/IstioWizards/IstioWizardDropdown.tsx
  src/components/IstioWizards/ThreeScaleIntegration.tsx
  src/components/IstioWizards/__tests__/ThreeScaleIntegration.test.ts
  src/config/Config.ts
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/services/Api.ts
  src/types/ThreeScale.ts
Labels: PR Required :stop_sign:

#1189 KIALI-2849 Tracing options still appear when removed in the backend
  src/app/AuthenticationController.tsx
  src/components/Nav/Menu.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
Labels: bug :bug:

#1188 KIALI-2851 Tracing tab when tracing is disabled
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
Labels: bug :bug:

#1171 KIALI-2840 Redesign Service Details
  src/components/BreadcrumbView/BreadcrumbView.tsx
  src/components/Pf/PfTitle.tsx
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/AppDetails/AppInfo.tsx
  src/pages/AppDetails/AppInfo/AppDescription.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoCard.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoCard.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
  src/styles/_overrides.scss
Labels: enhancement :rocket:, ux-review :pencil2:

#1191 KIALI-2728 Introduce Desired/Current/Available Pod Status details
  src/components/Health/__tests__/HealthIndicator.test.tsx
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
  src/types/Health.ts
  src/types/__tests__/Health.test.ts
Labels: PR Required :stop_sign:, bug :bug:

#1194 KIALI-2899 Upgrade react-router-dom
  package.json
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/GraphFilter/GraphFilter.tsx
  src/components/Nav/Menu.tsx
  src/components/Nav/NavUtils.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
  yarn.lock
Labels: Library Change :books:

#1014 Add tippy.js for cytoscape context menu on Nodes/Edges
  package.json
  src/app/App.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.scss
  src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
  yarn.lock
Labels: Library Change :books:, ux-review :pencil2:

#1195 KIALI-2893 Show the traces tab if jaeger is configured but applicatio…
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
Labels: bug :bug:

#1215 KIALI-2919 Allows context menu to use react components.
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/CytoscapeGraph/CytoscapeContextMenu.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
  src/pages/Graph/GraphPage.tsx
Labels: Refactor :recycle:

#1213 KIALI-2570 Add Selector labels to Service Details page
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/types/ServiceInfo.ts
Labels: PR Required :stop_sign:

#1220 KIALI-2795 Automaticaly refresh the mesh-wide TLS lock in the masthead
  src/actions/KialiAppAction.ts
  src/actions/MeshTlsActions.ts
  src/app/AuthenticationController.tsx
  src/components/MTls/MeshMTLSStatus.tsx
  src/config/Config.ts
  src/reducers/MeshTlsState.ts
  src/reducers/index.ts
  src/services/Api.ts
  src/store/ConfigStore.ts
  src/store/Selectors.ts
  src/store/Store.ts
Labels: PR Required :stop_sign:

#1209 KIALI-2911 Add options to menu in graph
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/CytoscapeGraph/CytoscapeContextMenu.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.scss
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/JaegerIntegration/RouteHelper.ts
  src/styles/index.scss
Labels: enhancement :rocket:, ux-review :pencil2:

#1229 KIALI-2948 Chart expand link overlaps chart
  src/components/Metrics/MetricsChartBase.tsx
Labels: bug :bug:
