Repository kiali/kiali-ui, pull requests merged in 2019-09, with the labels that each got.

#1392 Update patternfly charts to 4.7.9 in order to have ChartBullet
  package.json
  yarn.lock
Labels: do not merge

#1401 Kiali#1631 Polyfills window.customElements
  package.json
  src/index.tsx
  src/polyfills.ts
  yarn.lock
Labels: library change

#1386 Add incoming traffic summary to graph side panel
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/GraphFilter/GraphFind.tsx
  src/components/SummaryPanel/RateChart.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/types/Graph.ts
Labels: team/saturn

#1403 Migrate the cytoscape toolbar to PF4
  src/components/CytoscapeGraph/CytoscapeToolbar.tsx
  src/pages/Graph/GraphPage.tsx
Labels: team/saturn

#1417 Fix app counter in the side panel and add versions counter
  src/pages/Graph/SummaryPanelGraph.tsx
Labels: team/saturn

#1413 Fix error showing advanced options in Jaeger
  src/components/JaegerIntegration/JaegerToolbar.tsx
  src/components/JaegerIntegration/TagsControl.tsx
  src/components/JaegerIntegration/__tests__/__snapshots__/TagsControl.test.tsx.snap
Labels: backport/v1.0, backport/v1.4

#1419 Allow customized links to Grafana (front)
  src/components/Metrics/IstioMetrics.tsx
  src/types/GrafanaInfo.ts
Labels: backend changes required

#1429 PF3->PF4 Migrate Matching Routing Wizard
  package.json
  src/components/IstioWizards/MatchingRouting.tsx
  src/components/IstioWizards/MatchingRouting/MatchBuilder.tsx
  src/components/IstioWizards/MatchingRouting/Matches.tsx
  src/components/IstioWizards/MatchingRouting/RuleBuilder.tsx
  src/components/IstioWizards/MatchingRouting/Rules.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  yarn.lock
Labels: library change

#1394 [PF4] KIALI-1635 Migrate validations to PF4 from Istio Page
  src/components/Details/DetailObject.tsx
  src/components/Details/__tests__/DetailObject.test.tsx
  src/components/Details/__tests__/__snapshots__/DetailObject.test.tsx.snap
  src/components/Validations/GlobalValidation.tsx
  src/components/Validations/TooltipValidation.tsx
  src/components/Validations/Validation.scss
  src/components/Validations/Validation.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceDetail.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/types/DestinationRuleValidator.ts
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/services/__mockData__/getServiceDetail.ts
  src/types/IstioObjects.ts
  src/types/ServiceInfo.ts
Labels: team/jupiter

#1432 Use Grafana Links in custom dashboards
  package.json
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/GrafanaLinks.tsx
  src/components/Metrics/IstioMetrics.tsx
  src/components/Metrics/__tests__/CustomMetrics.test.tsx
  src/components/Metrics/__tests__/IstioMetrics.test.tsx
  src/types/GrafanaInfo.ts
  yarn.lock
Labels: backend changes required

#1423 [PF4] KIALI-1635 Summary Validation popover moved to PF4
  src/components/ConfigValidation/ConfigIndicator.tsx
  src/components/Health/Helper.ts
  src/components/Validations/Validation.tsx
  src/components/Validations/ValidationList.tsx
  src/components/Validations/ValidationSummary.tsx
  src/components/VirtualList/Renderers.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDestinationRules.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoVirtualServices.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoRouteVirtualServices.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
Labels: team/jupiter

#1436 Support request_duration_milliseconds for latency reporting in mixer-less telemetry
  src/components/SummaryPanel/ResponseTimeChart.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
Labels: backend changes required, team/saturn

#1439 PF3->PF4 Move Weighted Routing content
  package.json
  src/components/IstioWizards/Slider/BootstrapSlider.tsx
  src/components/IstioWizards/Slider/DropdownMenu.tsx
  src/components/IstioWizards/Slider/Slider.tsx
  src/components/IstioWizards/SuspendTraffic.tsx
  src/components/IstioWizards/WeightedRouting.tsx
  yarn.lock
Labels: library change

#1442 Re-enable tooltips in overview sparklines, upgrade k-charted
  package.json
  src/pages/Overview/OverviewCardBars.tsx
  src/pages/Overview/OverviewCardSparkline.tsx
  yarn.lock
Labels: library change

#1446 Trivial: Better align the Graph Legend Close box.
  src/components/GraphFilter/GraphLegend.tsx
  src/components/GraphFilter/__tests__/__snapshots__/GraphLegend.test.tsx.snap
Labels: team/saturn, ux review required

#1443 Removed some information from the breadcrumbs
  src/components/BreadcrumbView/BreadcrumbView.tsx
Labels: team/saturn

#1444 When building the breadcrumbs, consider "." in the item name
  src/components/BreadcrumbView/BreadcrumbView.tsx
Labels: team/saturn
