Repository kiali/kiali-ui, pull requests merged in 2020-11, with the labels that each got.

#1985 Display more info about the Pod phase/status when looking at workload pods
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
  src/types/IstioObjects.ts
Labels: backend changes required, team/saturn

#1991 Fix pod logs issue when pod had no proxy
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Labels: team/saturn

#1994 Make sure API logout completes before submitting openshift logout form
  src/components/Nav/Masthead/UserDropdown.tsx
Labels: backend changes required, backport/v1.12, backport/v1.24, team/saturn

#1995 Remove label filter by clicking on the label is not working
  src/components/Filters/StatefulFilters.tsx
  src/components/Filters/__tests__/StatefulFilters.test.tsx
  src/components/VirtualList/Renderers.tsx
Labels: backport/v1.24, team/jupiter

#1996 [1.24] Remove label filter by clicking on the label is not working
  src/components/Filters/StatefulFilters.tsx
  src/components/Filters/__tests__/StatefulFilters.test.tsx
  src/components/VirtualList/Renderers.tsx
Labels: backport/v1.24, team/jupiter

#1997 [1.24] Make sure API logout completes before submitting openshift logout form
  src/components/Nav/Masthead/UserDropdown.tsx
Labels: team/saturn

#1998 [1.12] Make sure API logout completes before submitting openshift logout form
  src/components/Nav/Masthead/UserDropdown.tsx
Labels: team/saturn

#2001 Revise namespace selector (add select all)
  src/components/NamespaceDropdown.tsx
Labels: team/saturn

#2003 OSSM-310 Fix lost settings on metrics page
  src/components/Metrics/Helper.ts
Labels: backport/v1.24

#1999 Add one more state for the Istio component status
  src/components/IstioStatus/IstioComponentStatus.tsx
  src/types/IstioStatus.ts
Labels: backend changes required

#2002 Merge k-charted in kiali
  package.json
  src/components/Charts/ChartWithLegend.tsx
  src/components/Charts/Container.tsx
  src/components/Charts/CustomTooltip.tsx
  src/components/Charts/Dashboard.tsx
  src/components/Charts/KChart.tsx
  src/components/Charts/SparklineChart.tsx
  src/components/JaegerIntegration/JaegerScatter.tsx
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/GrafanaLinks.tsx
  src/components/Metrics/Helper.ts
  src/components/Metrics/IstioMetrics.tsx
  src/components/Metrics/SpanOverlay.ts
  src/components/Metrics/__tests__/IstioMetrics.test.tsx
  src/components/MetricsOptions/MetricsRawAggregation.tsx
  src/components/MetricsOptions/MetricsSettings.ts
  src/components/MetricsOptions/MetricsSettingsDropdown.tsx
  src/components/SummaryPanel/RateChart.tsx
  src/components/SummaryPanel/ResponseTimeChart.tsx
  src/components/SummaryPanel/RpsChart.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNodeTraffic.tsx
  src/pages/Overview/NamespaceInfo.ts
  src/pages/Overview/OverviewCardContentExpanded.tsx
  src/pages/Overview/OverviewCardSparkline.tsx
  src/pages/Overview/OverviewPage.tsx
  src/services/Api.ts
  src/types/Dashboards.ts
  src/types/GrafanaInfo.ts
  src/types/Metrics.ts
  src/types/MetricsOptions.ts
  src/types/Overlay.ts
  src/types/Runtimes.ts
  src/types/VictoryChartInfo.ts
  src/types/__mocks__/Charts.mock.ts
  src/types/__mocks__/Dashboards.mock.ts
  src/utils/Formatter.ts
  src/utils/Graphing.ts
  src/utils/TimeSeriesUtils.ts
  src/utils/VictoryChartsUtils.ts
  src/utils/VictoryEvents.ts
  src/utils/__tests__/VictoryChartsUtils.test.ts
  yarn.lock
Labels: backend changes required

#2000 [multi-cluster] Add a "Mesh" page
  src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
  src/components/Nav/RenderPage.tsx
  src/config/Config.ts
  src/pages/Mesh/MeshPage.tsx
  src/routes.tsx
  src/services/Api.ts
  src/types/Mesh.ts
  src/types/Routes.ts
Labels: backend changes required, do not merge, team/saturn
