Repository kiali/kiali-ui, pull requests merged in 2020-10, with the labels that each got.

#1959 Fix tooltip not being rendered in Workload pods
  src/components/Validations/ValidationList.tsx
Labels: backport/v1.24

#1960 Sync VS/GW hosts on new GW
  src/components/IstioWizards/RequestRouting/Rules.tsx
  src/components/IstioWizards/ServiceWizard.tsx
Labels: backport/v1.24

#1968 Show Principals in edge side panel, when available.
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/store/Selectors/GraphData.ts
  src/types/Graph.ts
Labels: team/saturn

#1884 Add proxy status in the health
  src/components/Health/__tests__/HealthIndicator.test.tsx
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/components/Validations/ValidationStack.tsx
  src/pages/WorkloadDetails/WorkloadInfo/PodStatus.scss
  src/pages/WorkloadDetails/WorkloadInfo/PodStatus.tsx
  src/pages/WorkloadDetails/WorkloadInfo/ProxyStatusList.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/ProxyStatusList.test.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/ProxyStatusList.test.tsx.snap
  src/types/Health.ts
  src/types/IstioObjects.ts
  src/types/ServiceInfo.ts
  src/types/__tests__/Health.test.ts
Labels: backend changes required

#1957 add 'healthy' operand to graph find/hind / ensure health for graph nodes is part of the overall graph fetch
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/TrafficList/TrafficDetails.tsx
  src/pages/AppDetails/AppInfo.tsx
  src/pages/Graph/GraphHelpFind.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/pages/Overview/OverviewPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
  src/services/GraphDataSource.ts
  src/services/__tests__/GraphDataSource.test.ts
  src/store/Selectors/GraphData.ts
  src/types/Graph.ts
Labels: do not merge, team/saturn

#1882 Support setting history mode by parameter
  src/app/History.ts
Labels: team/saturn

#1973 Add true fullscreen capability to logging tab
  package.json
  src/pages/WorkloadDetails/WorkloadInfo/FullScreenLogModal.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
  yarn.lock
Labels: library change, team/saturn, ux review required

#1976 Remove Mixer + RBAC + 3Scale deps
  src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
  src/components/IstioActions/IstioActionsNamespaceDropdown.tsx
  src/components/IstioWizards/ThreeScaleCredentials.tsx
  src/components/IstioWizards/WizardActions.ts
  src/components/IstioWizards/WorkloadWizard.tsx
  src/components/IstioWizards/WorkloadWizardDropdown.tsx
  src/components/Nav/RenderPage.tsx
  src/config/Config.ts
  src/config/ServerConfig.ts
  src/pages/IstioConfigList/FiltersAndSorts.ts
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/pages/extensions/threescale/ThreeScaleNew/ThreeScaleNewPage.tsx
  src/routes.tsx
  src/types/IstioConfigDetails.ts
  src/types/IstioConfigList.ts
  src/types/IstioObjects.ts
  src/types/ServerConfig.ts
  src/utils/IstioConfigUtils.ts
Labels: backend changes required

#1977 workload logs - use new LogEntry and Duration support
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
  src/services/Api.ts
  src/types/Common.ts
  src/types/IstioObjects.ts
Labels: backend changes required, team/saturn

#1980 Fix wrong timestamp being use for traces query in graph
  src/pages/Graph/SummaryPanelNode.tsx
Labels: backport/v1.24

#1989 Stop animation on hovered edge so a user can easily read the label
  src/components/CytoscapeGraph/TrafficAnimation/TrafficRenderer.ts
  src/components/CytoscapeGraph/graphs/GraphHighlighter.ts
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
Labels: team/saturn
