Repository kiali/kiali-ui, pull requests merged in 2020-09, with the labels that each got.

#1901 Add IstioConfig under Workload Details
  src/components/IstioConfigSubList/IstioConfigSubList.tsx
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadServices.tsx
  src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentCreatePage.tsx
  src/pages/extensions/threescale/ThreeScaleNew/ThreeScaleNewPage.tsx
  src/services/Api.ts
  src/types/IstioConfigList.ts
  src/types/ServiceInfo.ts
Labels: backend changes required

#1903 Enhance graph find/hide expression power
  src/pages/Graph/GraphHelpFind.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx
Labels: team/saturn

#1906 Improve graph find/hide autocomplete
  src/pages/Graph/GraphHelpFind.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/utils/AutoComplete.ts
Labels: team/saturn

#1915 Add Status field into Istio Objects
  src/components/Validations/Validation.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/IstioStatusMessageList.tsx
  src/types/IstioObjects.ts
Labels: backend changes required

#1927 Patternfly minor bump
  package.json
  yarn.lock
Labels: library change

#1925 Add Support for requests with no response
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/components/Health/__tests__/HealthIndicator.test.tsx
  src/components/Pf/PfColors.tsx
  src/components/SummaryPanel/InOutRateTable.tsx
  src/components/SummaryPanel/RateChart.tsx
  src/components/SummaryPanel/RateTable.tsx
  src/pages/Graph/SummaryLink.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNodeTraffic.tsx
  src/store/Selectors/GraphData.ts
  src/types/ErrorRate/ErrorRate.ts
  src/types/Graph.ts
  src/utils/TrafficRate.ts
Labels: backend changes required, team/saturn

#1932 Refactor Istio Details: Bump Editor + Overview Drawer
  package.json
  src/components/IstioActions/IstioActionsButtons.tsx
  src/components/MessageCenter/MessageCenter.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleOverview.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceOverview.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
  src/pages/IstioConfigDetails/ValidationReferences.tsx
  src/types/AceValidations.ts
  src/types/IstioConfigDetails.ts
  src/types/__tests__/AceValidations.test.ts
  src/utils/AlertUtils.ts
  src/utils/IstioValidationUtils.ts
  yarn.lock
Labels: backport/v1.24, library change

#1935 Fix empty layout for pods/services
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadServices.tsx
Labels: backport/v1.24

#1936 Fix reset filters on breadcrumb
  src/components/BreadcrumbView/BreadcrumbView.tsx
  src/components/Filters/StatefulFilters.tsx
Labels: backport/v1.24

#1940 Fix z-index on Istio actions
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Labels: backport/v1.24

#1941 Fix AuthorizationPolicy DENYALL and ALLOWALL
  src/components/IstioWizards/WizardActions.ts
  src/pages/IstioConfigNew/AuthorizationPolicyForm.tsx
Labels: backend changes required, backport/v1.24

#1933 Trace on graph: comply to opentracing standard
  src/components/CytoscapeGraph/CytoscapeTrace.ts
  src/components/JaegerIntegration/JaegerHelper.ts
  src/pages/Graph/SummaryPanelTraceDetails.tsx
Labels: team/jupiter

#1946 Remove ServiceMeshPolicy and SMRbacConfig for Maistra installations
  src/components/VirtualList/Config.ts
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigList/FiltersAndSorts.ts
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/types/IstioConfigDetails.ts
  src/types/IstioConfigList.ts
  src/types/IstioObjects.ts
  src/utils/IstioConfigUtils.ts
Labels: backend changes required

#1943 Migrate detail view traffic tab to standard list look+feel
  src/components/CytoscapeGraph/CytoscapeTrace.ts
  src/components/Details/DetailedTrafficList.tsx
  src/components/Details/__tests__/DetailedTrafficList.test.tsx
  src/components/FilterList/FilterComponent.tsx
  src/components/Metrics/TrafficDetails.tsx
  src/components/Metrics/__tests__/TrafficDetails.test.tsx
  src/components/TrafficList/FiltersAndSorts.ts
  src/components/TrafficList/TrafficDetails.tsx
  src/components/TrafficList/TrafficListComponent.tsx
  src/components/VirtualList/VirtualList.tsx
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/AppDetails/AppInfo.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Overview/OverviewPage.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/services/GraphDataSource.ts
  src/types/ErrorRate/TrafficHealth.ts
  src/types/SortFilters.ts
Labels: team/saturn

#1949 IstioConfig: ValidationMessages are not mandatory
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/types/IstioObjects.ts
Labels: backport/v1.24
