Repository kiali/kiali-ui, pull requests merged in 2020-06, with the labels that each got.

#1810 Separate jaeger queries and kiali tracing queries
  src/app/History.ts
  src/components/JaegerIntegration/RouteHelper.ts
  src/components/JaegerIntegration/ServiceTraces.tsx
  src/components/JaegerIntegration/TracesFetcher.ts
  src/services/Api.ts
  src/types/Tracing.ts
Labels: backend changes required

#1812 Expose Istio Telemetry Version to Public Config
  src/config/ServerConfig.ts
  src/types/ServerConfig.ts
Labels: backend changes required

#1813 Add EnvoyFilter,AttributeManifest,HttpApiSpec{Binding}
  src/components/VirtualList/Config.ts
  src/pages/IstioConfigList/FiltersAndSorts.ts
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/types/IstioConfigDetails.ts
  src/types/IstioConfigList.ts
  src/types/IstioObjects.ts
  src/utils/IstioConfigUtils.ts
Labels: backend changes required, backport/v1.18

#1799 Add support for OpenId strategy for authentication
  src/actions/LoginThunkActions.ts
  src/app/AuthenticationController.tsx
  src/components/Nav/Masthead/UserDropdown.tsx
  src/config/AuthenticationConfig.ts
  src/pages/Login/LoginPage.tsx
  src/services/Login.ts
  src/types/Auth.ts
Labels: team/saturn

#1818 Show message if Kiali is configured with LDAP or login strategy for authentication
  src/pages/Login/LoginPage.tsx
  src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
Labels: team/saturn

#1821 Fix bug in Hide logs when backspace or delete is used to reset
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Labels: team/saturn

#1822 Remove subtypes. Add Instances/Handlers
  src/components/Link/IstioObjectLink.tsx
  src/components/VirtualList/Config.ts
  src/components/VirtualList/Renderers.tsx
  src/config/Config.ts
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigList/FiltersAndSorts.ts
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/services/Api.ts
  src/types/IstioConfigDetails.ts
  src/types/IstioConfigList.ts
  src/types/IstioObjects.ts
  src/utils/IstioConfigUtils.ts
Labels: backend changes required, team/jupiter

#1824 Show graph JSON in debug dialog
  src/actions/ActionKeys.ts
  src/actions/GraphActions.ts
  src/pages/Graph/GraphPage.tsx
  src/reducers/GraphDataState.ts
  src/reducers/__tests__/GraphDataState.test.ts
  src/store/Store.ts
Labels: team/saturn

#1811 Fix some layout issues with logs tab
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Labels: team/saturn

#1828 Click on namespace labels crashes
  src/components/Filters/StatefulFilters.tsx
  src/components/VirtualList/Renderers.tsx
  src/components/VirtualList/VirtualItem.tsx
  src/components/VirtualList/VirtualList.tsx
  src/pages/Overview/OverviewPage.tsx
  src/pages/Overview/OverviewToolbar.tsx
  src/pages/Overview/__tests__/__snapshots__/OverviewPage.test.tsx.snap
Labels: do not merge

#1826 Navigation to other detail pages using mini-graph
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/MiniGraphCard.tsx
  src/pages/Graph/GraphPage.tsx
  src/types/Graph.ts
Labels: team/saturn

#1834 Fix test to determine OpenId/OAuth preparation
  src/services/Login.ts
Labels: team/saturn
