Repository kiali/kiali-ui, pull requests merged in 2020-01, with the labels that each got.

#1598 Fix yarn.lock for prop-types.
  yarn.lock
Labels: team/saturn

#1604 Fix scroll in Overview page
  src/components/Nav/Page/RenderComponentScroll.tsx
  src/pages/Overview/OverviewPage.tsx
Labels: team/jupiter

#1601 Move Workload type filter to typeahead selector
  src/components/Filters/CommonFilters.ts
  src/components/Filters/StatefulFilters.tsx
  src/pages/IstioConfigList/FiltersAndSorts.ts
  src/pages/Overview/Filters.ts
  src/pages/WorkloadList/FiltersAndSorts.ts
  src/types/Filters.ts
Labels: team/jupiter

#1599 UX suggestions for Health card in detail pages
  src/components/Health/Health.scss
  src/components/Health/HealthDetails.tsx
  src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/pages/AppDetails/AppInfo/AppDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
  src/types/Health.ts
Labels: team/saturn

#1577 Replace traces iFrame with a Kiali React component
  src/app/AuthenticationController.tsx
  src/app/History.ts
  src/assets/img/jaeger-icon.svg
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
  src/components/JaegerIntegration/JaegerIntegration.tsx
  src/components/JaegerIntegration/JaegerResults/JaegerItem.tsx
  src/components/JaegerIntegration/JaegerResults/JaegerTraceTitle.tsx
  src/components/JaegerIntegration/JaegerResults/SpanDetail.tsx
  src/components/JaegerIntegration/JaegerResults/SpanTable.tsx
  src/components/JaegerIntegration/JaegerResults/SpanTabsTags.tsx
  src/components/JaegerIntegration/JaegerResults/SpanTags.tsx
  src/components/JaegerIntegration/JaegerResults/_SpanTable.scss
  src/components/JaegerIntegration/JaegerResults/index.tsx
  src/components/JaegerIntegration/JaegerResults/transform.ts
  src/components/JaegerIntegration/JaegerScatter.tsx
  src/components/JaegerIntegration/JaegerToolbar.tsx
  src/components/JaegerIntegration/JaegerTracesIframe.tsx
  src/components/JaegerIntegration/LookBack.tsx
  src/components/JaegerIntegration/RightToolbar.tsx
  src/components/JaegerIntegration/RouteHelper.ts
  src/components/JaegerIntegration/ServiceDropdown.tsx
  src/components/JaegerIntegration/TagsControl.tsx
  src/components/JaegerIntegration/__tests__/JaegerToolbar.test.tsx
  src/components/JaegerIntegration/__tests__/LookBack.test.tsx
  src/components/JaegerIntegration/__tests__/RightToolbar.test.tsx
  src/components/JaegerIntegration/__tests__/ServiceDropdown.test.tsx
  src/components/JaegerIntegration/__tests__/TagsControl.test.tsx
  src/components/JaegerIntegration/__tests__/__snapshots__/RightToolbar.test.tsx.snap
  src/components/JaegerIntegration/__tests__/__snapshots__/ServiceDropdown.test.tsx.snap
  src/components/JaegerIntegration/__tests__/__snapshots__/TagsControl.test.tsx.snap
  src/components/JaegerIntegration/_jaegerIntegration.scss
  src/components/JaegerIntegration/index.tsx
  src/components/Nav/Menu.tsx
  src/components/Nav/Navigation.tsx
  src/config/Config.ts
  src/helpers/TracesHelper.ts
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceTraces.tsx
  src/pages/ServiceJaeger/ServiceJaegerPage.tsx
  src/reducers/JaegerState.ts
  src/reducers/__tests__/JaegerStateReducer.test.ts
  src/routes.tsx
  src/services/Api.ts
  src/store/Store.ts
  src/styles/index.scss
  src/types/JaegerInfo.ts
Labels: backend changes required, backport/v1.12, team/jupiter

#1605 Replace traces iFrame with a Kiali React component
  src/app/AuthenticationController.tsx
  src/app/History.ts
  src/assets/img/jaeger-icon.svg
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
  src/components/JaegerIntegration/JaegerIntegration.tsx
  src/components/JaegerIntegration/JaegerResults/JaegerItem.tsx
  src/components/JaegerIntegration/JaegerResults/JaegerTraceTitle.tsx
  src/components/JaegerIntegration/JaegerResults/SpanDetail.tsx
  src/components/JaegerIntegration/JaegerResults/SpanTable.tsx
  src/components/JaegerIntegration/JaegerResults/SpanTabsTags.tsx
  src/components/JaegerIntegration/JaegerResults/SpanTags.tsx
  src/components/JaegerIntegration/JaegerResults/_SpanTable.scss
  src/components/JaegerIntegration/JaegerResults/index.tsx
  src/components/JaegerIntegration/JaegerResults/transform.ts
  src/components/JaegerIntegration/JaegerScatter.tsx
  src/components/JaegerIntegration/JaegerToolbar.tsx
  src/components/JaegerIntegration/JaegerTracesIframe.tsx
  src/components/JaegerIntegration/LookBack.tsx
  src/components/JaegerIntegration/RightToolbar.tsx
  src/components/JaegerIntegration/RouteHelper.ts
  src/components/JaegerIntegration/ServiceDropdown.tsx
  src/components/JaegerIntegration/TagsControl.tsx
  src/components/JaegerIntegration/__tests__/JaegerToolbar.test.tsx
  src/components/JaegerIntegration/__tests__/LookBack.test.tsx
  src/components/JaegerIntegration/__tests__/RightToolbar.test.tsx
  src/components/JaegerIntegration/__tests__/ServiceDropdown.test.tsx
  src/components/JaegerIntegration/__tests__/TagsControl.test.tsx
  src/components/JaegerIntegration/__tests__/__snapshots__/RightToolbar.test.tsx.snap
  src/components/JaegerIntegration/__tests__/__snapshots__/ServiceDropdown.test.tsx.snap
  src/components/JaegerIntegration/__tests__/__snapshots__/TagsControl.test.tsx.snap
  src/components/JaegerIntegration/_jaegerIntegration.scss
  src/components/JaegerIntegration/index.tsx
  src/components/Nav/Menu.tsx
  src/components/Nav/Navigation.tsx
  src/config/Config.ts
  src/helpers/TracesHelper.ts
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceTraces.tsx
  src/pages/ServiceJaeger/ServiceJaegerPage.tsx
  src/reducers/JaegerState.ts
  src/reducers/__tests__/JaegerStateReducer.test.ts
  src/routes.tsx
  src/services/Api.ts
  src/store/Store.ts
  src/styles/index.scss
  src/types/JaegerInfo.ts
Labels: backend changes required

#1606 Move scroll from VirtualList to parent container
  package.json
  src/components/Nav/Page/RenderContent.tsx
  src/components/VirtualList/VirtualItem.tsx
  src/components/VirtualList/VirtualList.tsx
  src/components/VirtualList/VirtualTable.tsx
  src/pages/AppList/AppListComponent.tsx
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
  src/pages/WorkloadList/WorkloadListComponent.tsx
  yarn.lock
Labels: backport/v1.12, team/jupiter

#1613 Traces tab should be visible just with InClusterURL configured
  src/app/AuthenticationController.tsx
Labels: backend changes required, backport/v1.12

#1615 Update traces when refresh
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
Labels: backport/v1.12

#1623 Remove lint in build:prod
  package.json
Labels: backport/v1.12

#1585 Graph Replay
  package.json
  src/actions/ActionKeys.ts
  src/actions/GraphDataThunkActions.ts
  src/actions/UserSettingsActions.ts
  src/app/App.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/DurationDropdown/DurationDropdown.tsx
  src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/components/IstioWizards/Slider/BootstrapSlider.tsx
  src/components/IstioWizards/Slider/Slider.tsx
  src/components/IstioWizards/WeightedRouting.tsx
  src/components/MTls/MeshMTLSStatus.tsx
  src/components/Nav/NavUtils.tsx
  src/components/Refresh/Refresh.tsx
  src/components/Time/LocalTime.tsx
  src/components/Time/Replay.tsx
  src/components/Time/TimeRange.tsx
  src/components/Time/Utils.tsx
  src/components/Time/_Time.scss
  src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
  src/config/KialiIcon.tsx
  src/config/ServerConfig.ts
  src/pages/Graph/GraphHelpTour.ts
  src/pages/Graph/GraphLegend.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  src/pages/Graph/GraphToolbar/__tests__/__snapshots__/GraphLegend.test.tsx.snap
  src/pages/Overview/OverviewPage.tsx
  src/pages/Overview/OverviewToolbar.tsx
  src/reducers/UserSettingsState.ts
  src/reducers/__tests__/UserSettingsState.test.ts
  src/store/Selectors.ts
  src/store/Store.ts
  src/styles/_overrides.scss
  src/styles/index.scss
  src/types/Common.ts
  src/utils/RateIntervals.ts
  yarn.lock
Labels: team/saturn

#1632 Add id to the loading spinner
  src/components/PfSpinner.tsx
Labels: backport/v1.12

#1633 Add id to the loading spinner
  src/components/PfSpinner.tsx
Labels: do not merge

#1634 Service Details load Error when Jaeger is configured wrongly
  src/app/AuthenticationController.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
Labels: backport/v1.12

#1617 Add structure to create new Istio config resources at namespace level
  src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
  src/components/IstioActions/IstioActionsDropdown.tsx
  src/components/IstioActions/IstioActionsNamespaceDropdown.tsx
  src/components/IstioWizards/IstioWizardActions.ts
  src/config/Config.ts
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/IstioConfigNew/GatewayForm.tsx
  src/pages/IstioConfigNew/IstioConfigNewPage.tsx
  src/pages/IstioConfigNew/SidecarForm.tsx
  src/routes.tsx
  src/services/Api.ts
  src/types/IstioConfigDetails.ts
  src/types/IstioObjects.ts
  src/utils/IstioConfigUtils.ts
  src/utils/__tests__/IstioConfigUtils.test.ts
Labels: team/jupiter

#1639 Bump k-charted 0.4.3
  package.json
  yarn.lock
Labels: backport/v1.12

#1627 Make sidepanel rate chart graph colors more easily distinguished.
  src/components/Pf/PfColors.tsx
  src/components/SummaryPanel/RateChart.tsx
Labels: team/saturn

#1643 Graph side-panel UX review
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/SummaryPanel/InOutRateTable.tsx
  src/components/SummaryPanel/RateChart.tsx
  src/components/SummaryPanel/RateTable.tsx
  src/components/Tab/SimpleTabs.tsx
  src/pages/Graph/SummaryLink.tsx
  src/pages/Graph/SummaryPanel.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/pages/Graph/_Graph.scss
  src/styles/index.scss
Labels: team/saturn
