Repository kiali/kiali-ui, pull requests merged in 2020-07, with the labels that each got.

#1842 In kiosk mode，the main header should not be shown
  src/components/Nav/Navigation.tsx
  src/components/Nav/__tests__/Navigation.test.tsx
  src/components/Nav/__tests__/RenderPage.test.tsx
  src/styles/_overrides.scss
Labels: do not merge

#1843 Upgrade Cytoscape to the latest version
  package.json
  yarn.lock
Labels: library change, team/saturn

#1844 Remove namespace/service path params for single trace
  src/components/JaegerIntegration/ServiceTraces.tsx
  src/config/Config.ts
  src/services/Api.ts
Labels: backend changes required

#1823 Add Regex filter for Show/hide.
  src/config/KialiIcon.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Labels: team/saturn

#1837 Traces list in side-panel
  src/app/History.ts
  src/components/JaegerIntegration/JaegerResults/FormattedTraceInfo.ts
  src/components/JaegerIntegration/JaegerResults/JaegerItem.tsx
  src/components/JaegerIntegration/JaegerResults/JaegerTraceTitle.tsx
  src/components/JaegerIntegration/TraceListItem.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/pages/Graph/SummaryPanelNodeTraces.tsx
  src/pages/Graph/SummaryPanelNodeTraffic.tsx
  src/utils/SearchParamUtils.ts
Labels: team/jupiter

#1836 Introduce operation aggregate nodes into graph and side panel
  src/actions/ActionKeys.ts
  src/actions/GraphToolbarActions.ts
  src/app/History.ts
  src/assets/img/legend/aggregate.svg
  src/assets/img/legend/virtualservice.svg
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/CytoscapeGraphSelector.ts
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/components/CytoscapeGraph/MiniGraphCard.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/Details/DetailedTrafficList.tsx
  src/components/Metrics/TrafficDetails.tsx
  src/components/Nav/NavUtils.tsx
  src/config/Config.ts
  src/config/Paths.ts
  src/pages/Graph/GraphHelpFind.tsx
  src/pages/Graph/GraphLegendData.ts
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx
  src/pages/Graph/GraphToolbar/__tests__/__snapshots__/GraphLegend.test.tsx.snap
  src/pages/Graph/SummaryLink.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/pages/Graph/SummaryPanelNodeTraffic.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
  src/reducers/GraphDataState.ts
  src/reducers/__tests__/GraphDataState.test.ts
  src/routes.tsx
  src/services/Api.ts
  src/services/GraphDataSource.ts
  src/services/__tests__/GraphDataSource.test.ts
  src/store/Selectors/GraphData.ts
  src/store/Store.ts
  src/types/Graph.ts
Labels: backend changes required, team/saturn

#1849 change op nodes from star to round-pentagon, and update legend
  src/assets/img/legend/aggregate.svg
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
Labels: team/saturn

#1854 Fix issue with suppressed error message
  src/pages/Graph/GraphToolbar/GraphFind.tsx
Labels: team/saturn

#1855 Fix graph losing focused node context after first refresh
  src/components/CytoscapeGraph/EmptyGraphLayout.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
Labels: team/jupiter

#1833 Workload detail actions + 3scale extension changes
  src/components/DefaultSecondaryMasthead/DefaultSecondaryMasthead.tsx
  src/components/IstioActions/IstioActionsNamespaceDropdown.tsx
  src/components/IstioWizards/ServiceWizard.tsx
  src/components/IstioWizards/ServiceWizardDropdown.tsx
  src/components/IstioWizards/ThreeScaleCredentials.tsx
  src/components/IstioWizards/ThreeScaleIntegration.tsx
  src/components/IstioWizards/WeightedRouting.tsx
  src/components/IstioWizards/WizardActions.ts
  src/components/IstioWizards/WorkloadWizard.tsx
  src/components/IstioWizards/WorkloadWizardDropdown.tsx
  src/components/Label/Label.tsx
  src/components/Nav/Menu.tsx
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/IstioConfigNew/IstioConfigNewPage.tsx
  src/pages/IstioConfigNew/PeerAuthenticationForm.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/pages/WorkloadList/WorkloadListComponent.tsx
  src/pages/extensions/threescale/ThreeScaleHandlerDetails/ThreeScaleHandlerDetailsPage.tsx
  src/pages/extensions/threescale/ThreeScaleHandlerList/ThreeScaleHandlerListPage.tsx
  src/pages/extensions/threescale/ThreeScaleNew/ThreeScaleNewPage.tsx
  src/routes.tsx
  src/services/Api.ts
  src/types/ServerConfig.ts
  src/types/ThreeScale.ts
Labels: backend changes required

#1856 Update lodash due to Snyk security report (#1847)
  package.json
  src/components/MetricsOptions/MetricsSettingsDropdown.tsx
  yarn.lock
Labels: backport/v1.12, team/saturn

#1857 Show namespace in ServiceEntry label, when appropriate
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
Labels: team/saturn

#1858 [v1.18 backport] Show namespace in ServiceEntry label, when appropriate (#1857)
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
Labels: backend changes required, backport/v1.18, team/saturn

#1862 View logs in fullscreen mode
  src/config/KialiIcon.tsx
  src/pages/WorkloadDetails/WorkloadInfo/FullScreenLogModal.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
  src/types/Common.ts
Labels: team/saturn

#1863 Bump k-charted 0.6.1-rc2 + default grouping on remote app
  package.json
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/Helper.ts
  src/components/Metrics/IstioMetrics.tsx
  yarn.lock
Labels: backend changes required
