Repository kiali/kiali-ui, pull requests merged in 2020-08, with the labels that each got.

#1866 Traces are being searched for by service name but apparently it's the…
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/JaegerIntegration/AppTraces.tsx
  src/components/JaegerIntegration/JaegerResults/JaegerItem.tsx
  src/components/JaegerIntegration/JaegerResults/SpanDetail.tsx
  src/components/JaegerIntegration/JaegerResults/SpanTable.tsx
  src/components/JaegerIntegration/TracesFetcher.ts
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/IstioMetrics.tsx
  src/components/Metrics/SpanOverlay.ts
  src/config/Config.ts
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/Graph/SummaryPanelNodeTraces.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/services/Api.ts
Labels: backend changes required

#1867 Don't use message center alerts for regex errors
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Labels: team/saturn

#1860 In-graph tracing: show trace details
  src/actions/JaegerThunkActions.ts
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/CytoscapeGraphSelector.ts
  src/components/CytoscapeGraph/CytoscapeTrace.ts
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/JaegerIntegration/JaegerHelper.ts
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/pages/Graph/SummaryPanelNodeTraces.tsx
  src/pages/Graph/SummaryPanelTraceDetails.tsx
  src/utils/SearchParamUtils.ts
Labels: team/jupiter

#1875 Add/Remove Auto Injection
  src/components/IstioWizards/WizardActions.ts
  src/config/Config.ts
  src/config/ServerConfig.ts
  src/pages/Overview/OverviewPage.tsx
  src/services/Api.ts
  src/types/ServerConfig.ts
Labels: backend changes required

#1876 Honor preset URL after OAuth/OICD login
  src/actions/ActionKeys.ts
  src/actions/LoginActions.ts
  src/app/AuthenticationController.tsx
  src/reducers/LoginState.ts
  src/store/ConfigStore.ts
  src/store/Store.ts
Labels: team/saturn

#1880 Align login text with website.
  src/pages/Login/LoginPage.tsx
  src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
Labels: team/saturn

#1883 Bump Lodash version.
  package.json
  yarn.lock
Labels: dependencies, team/saturn

#1861 remove login and ldap auth strategy
  src/app/StartupInitializer.tsx
  src/components/SessionTimeout/SessionTimeout.tsx
  src/config/AuthenticationConfig.ts
  src/pages/Login/LoginPage.tsx
  src/pages/Login/__tests__/LoginPage.test.tsx
  src/pages/Login/__tests__/__snapshots__/LoginPage.test.tsx.snap
  src/reducers/LoginState.ts
  src/services/Login.ts
  src/types/Auth.ts
Labels: backend changes required, team/saturn

#1894 Add info tooltip to Graph Security Display option.
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
Labels: team/saturn

#1895 Show login error message returned from back-end
  src/reducers/LoginState.ts
Labels: team/saturn

#1896 Add ability to drag nodes
  src/components/CytoscapeGraph/CytoscapeReactWrapper.tsx
  src/components/CytoscapeGraph/CytoscapeToolbar.tsx
  src/pages/Graph/GraphPage.tsx
Labels: team/saturn

#1898 Add simple AutoComplete for graph find/hide
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/utils/AutoComplete.ts
Labels: team/saturn
