Repository kiali/kiali-ui, pull requests merged in 2020-05, with the labels that each got.

#1760 Further attempts to eliminate graph drift on refresh when using graph hide
  src/pages/Graph/GraphToolbar/GraphFind.tsx
Labels: team/saturn

#1764 Snyk updates: react libs
  package.json
  src/components/DebugInformation/DebugInformation.tsx
  src/components/JaegerIntegration/JaegerResults/JaegerTraceTitle.tsx
  src/components/Metrics/__tests__/__snapshots__/IstioMetrics.test.tsx.snap
  src/components/Tour/TourStop.tsx
  src/components/VirtualList/VirtualList.tsx
  yarn.lock
Labels: library change, team/saturn

#1765 Log tailing capability (and horizontal scrolling)
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Labels: team/saturn

#1775 package updates to satisfy CVEs
  package.json
  yarn.lock
Labels: library change, team/saturn

#1774 Adding support to PeerAuthentication to IstioConfig section
  src/components/VirtualList/Config.ts
  src/pages/IstioConfigList/FiltersAndSorts.ts
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/types/IstioConfigDetails.ts
  src/types/IstioConfigList.ts
  src/types/IstioObjects.ts
  src/utils/IstioConfigUtils.ts
Labels: backend changes required

#1778 Add support for WorkloadEntry and RequestAuthentication
  src/components/VirtualList/Config.ts
  src/pages/IstioConfigList/FiltersAndSorts.ts
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/types/IstioConfigDetails.ts
  src/types/IstioConfigList.ts
  src/types/IstioObjects.ts
  src/utils/IstioConfigUtils.ts
Labels: backend changes required

#1779 Add log orientation layout
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Labels: team/saturn

#1781 Update lodash to the latest because there are known CVEs against earlier versions
  package.json
  yarn.lock
Labels: team/saturn

#1793 Adjust CSS align on overview list view
  src/pages/Overview/OverviewPage.tsx
Labels: team/jupiter

#1794 [v1.18]Adjust CSS align on overview list view
  src/pages/Overview/OverviewPage.tsx
Labels: team/jupiter

#1787 Show broken locks into edges without mtls in mesh-wide mtls scanarios
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
Labels: backport/v1.18, team/jupiter

#1803 v1.18 cherry-pick of #1787 - Show broken locks into edges without mtls
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
Labels: team/jupiter

#1795 Add Container selection back into Workload logs.
  package.json
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
  yarn.lock
Labels: team/saturn

#1790 Add a hide log lines feature(noise) when displaying workload logs
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Labels: team/saturn

#1796 Link from traces to workload logs can be wrong
  src/components/JaegerIntegration/JaegerResults/SpanTable.tsx
Labels: team/jupiter

#1804 Add {Peer,Request}Authentication objects to Create Istio Config
  src/components/IstioWizards/IstioWizardActions.ts
  src/components/MessageCenter/AlertDrawerMessage.tsx
  src/helpers/ValidationHelpers.ts
  src/pages/IstioConfigNew/AuthorizationPolicyForm.tsx
  src/pages/IstioConfigNew/AuthorizationPolicyForm/From/SourceBuilder.tsx
  src/pages/IstioConfigNew/AuthorizationPolicyForm/RuleList.tsx
  src/pages/IstioConfigNew/AuthorizationPolicyForm/To/OperationBuilder.tsx
  src/pages/IstioConfigNew/AuthorizationPolicyForm/When/ConditionBuilder.tsx
  src/pages/IstioConfigNew/GatewayForm.tsx
  src/pages/IstioConfigNew/IstioConfigNewPage.tsx
  src/pages/IstioConfigNew/PeerAuthenticationForm.tsx
  src/pages/IstioConfigNew/RequestAuthenticationForm.tsx
  src/pages/IstioConfigNew/RequestAuthorizationForm/JwtRuleBuilder.tsx
  src/pages/IstioConfigNew/RequestAuthorizationForm/JwtRuleList.tsx
  src/pages/IstioConfigNew/SidecarForm.tsx
  src/pages/extensions/threescale/ThreeScaleHandlerDetails/ThreeScaleHandlerDetailsPage.tsx
  src/types/IstioObjects.ts
  src/utils/IstioConfigUtils.ts
  src/utils/__tests__/IstioConfigUtils.test.ts
Labels: backend changes required, backport/v1.18

#1780 Labels filtering: "all of" / "any of" switch
  src/components/BreadcrumbView/BreadcrumbView.tsx
  src/components/FilterList/FilterHelper.ts
  src/components/FilterList/__tests__/ListPagesHelper.test.ts
  src/components/Filters/CommonFilters.ts
  src/components/Filters/LabelFilter.tsx
  src/components/Filters/StatefulFilters.tsx
  src/components/VirtualList/Renderers.tsx
  src/helpers/LabelFilterHelper.ts
  src/helpers/__tests__/LabelFilterHelper.test.ts
  src/pages/AppList/AppListComponent.tsx
  src/pages/AppList/FiltersAndSorts.ts
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  src/pages/Overview/Filters.ts
  src/pages/Overview/OverviewPage.tsx
  src/pages/Overview/OverviewStatus.tsx
  src/pages/Overview/__tests__/OverviewPage.test.tsx
  src/pages/ServiceList/FiltersAndSorts.ts
  src/pages/ServiceList/ServiceListComponent.tsx
  src/pages/WorkloadList/FiltersAndSorts.ts
  src/pages/WorkloadList/WorkloadListComponent.tsx
  src/pages/extensions/iter8/Iter8ExperimentList/FiltersAndSorts.ts
  src/types/Filters.ts
Labels: team/jupiter

#1798 Labels filtering: click on labels to filter
  src/components/Filters/CommonFilters.ts
  src/components/Filters/FilterStyles.tsx
  src/components/Filters/LabelFilter.tsx
  src/components/Filters/StatefulFilters.tsx
  src/components/VirtualList/Config.ts
  src/components/VirtualList/Renderers.tsx
  src/components/VirtualList/VirtualItem.tsx
  src/components/VirtualList/VirtualList.tsx
Labels: team/jupiter

#1800 Refactor Service|Workload|App Details
  src/components/CytoscapeGraph/MiniGraphCard.tsx
  src/components/JaegerIntegration/JaegerScatter.tsx
  src/components/JaegerIntegration/ServiceTraces.tsx
  src/components/JaegerIntegration/TracesFetcher.ts
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/IstioMetrics.tsx
  src/components/Metrics/TrafficDetails.tsx
  src/components/Metrics/__tests__/CustomMetrics.test.tsx
  src/components/Metrics/__tests__/IstioMetrics.test.tsx
  src/components/Metrics/__tests__/TrafficDetails.test.tsx
  src/components/RightActionBar/RightActionBar.tsx
  src/helpers/TracesHelper.ts
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/AppDetails/AppInfo.tsx
  src/pages/AppDetails/AppInfo/AppDescription.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/ServiceDetails/ServiceTraces.tsx
  src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/WorkloadDescription.test.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
  src/services/Api.ts
  src/services/GraphDataSource.ts
  src/services/__mocks__/MounterMocker.tsx
  src/types/JaegerInfo.ts
Labels: backend changes required, do not merge
