Repository kiali/kiali-ui, pull requests merged in 2020-03, with the labels that each got.

#1678 IstioConfigDetails: notify user when resource changes outside Kiali
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/types/IstioConfigDetails.ts
Labels: team/jupiter

#1673 Clean styles after PF4 migration
  package.json
  src/components/BreadcrumbView/BreadcrumbView.tsx
  src/components/IstioWizards/Slider/Slider.tsx
  src/components/IstioWizards/Slider/_Slider.scss
  src/components/Label/Labels.tsx
  src/components/Label/__tests__/__snapshots__/Labels.test.tsx.snap
  src/components/MessageCenter/AlertDrawer.tsx
  src/components/Nav/Page/RenderComponentScroll.tsx
  src/components/Nav/Page/RenderHeader.tsx
  src/components/Nav/SecondaryMasthead.tsx
  src/components/Refresh/Refresh.tsx
  src/components/ToolbarDropdown/ToolbarDropdown.tsx
  src/index.tsx
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/AppDetails/AppInfo.scss
  src/pages/AppDetails/AppInfo/AppDescription.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Graph/_Graph.scss
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceDetail.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/WorkloadDescription.test.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
  src/styles/_overrides.scss
  src/styles/index.scss
  yarn.lock
Labels: library change, refactor

#1676 Move "Show on graph" link down to the mini-graph card
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/MiniGraphCard.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/Pf/PfTitle.tsx
  src/pages/AppDetails/AppInfo/AppDescription.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx
  src/pages/Overview/OverviewCardLinks.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
Labels: team/saturn

#1687 Fixing Icon from info validations
  .gitignore
  .prettierignore
  src/components/IstioWizards/Slider/Slider.tsx
  src/components/IstioWizards/Slider/_Slider.scss
  src/components/IstioWizards/Slider/styles/default.css
  src/pages/AppDetails/AppInfo/AppDescription.scss
  src/pages/AppDetails/AppInfo/AppDescription.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.scss
Labels: team/jupiter

#1689 Improve edge side-panel Hosts tab
  src/components/SummaryPanel/ResponseHostsTable.tsx
Labels: team/saturn

#1661 Update Typescript to 3.8
  package.json
  src/components/PfSpinner.tsx
  src/pages/IstioConfigList/IstioConfigListComponent.tsx
  tsconfig.json
  yarn.lock
Labels: library change, team/saturn

#1697 Adding pficon FaceFont to be able to load icon into graph (#1693)
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/config/Icons.ts
  src/index.tsx
  src/routes.tsx
  src/styles/_fonts.scss
  src/styles/index.scss
  src/types/Routes.ts
Labels: backport/v1.12, team/saturn

#1706 Fix service link into Istio Object details page
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleDetail.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/ServiceLink.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/__tests__/ServiceLink.test.tsx
Labels: backport/v1.12

#1710 update react-datepicker (snyk recommended)
  package.json
  src/components/Time/Replay.tsx
  yarn.lock
Labels: team/saturn

#1717 Graph side panel fix
  src/pages/Graph/SummaryPanelGraph.tsx
Labels: team/saturn

#1715 Fix graph error when enabling response time edges in some cases.
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
Labels: team/saturn
