Repository kiali/kiali-ui, pull requests merged in 2020-12, with the labels that each got.

#2018 Enable the use of node.js 14.x for building/testing kiali-ui.
  package.json
Labels: team/saturn

#2006 Add envoy proxy config into pod level (workload page)
  src/components/Envoy/EnvoyModal.tsx
  src/components/Envoy/writers/BaseTable.tsx
  src/components/Envoy/writers/ClusterTable.ts
  src/components/Envoy/writers/ListenerTable.ts
  src/components/Envoy/writers/RouteTable.ts
  src/components/IstioWizards/WorkloadWizardDropdown.tsx
  src/config/Config.ts
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/services/Api.ts
  src/types/IstioObjects.ts
Labels: backend changes required

#2027 [v1.12] CVE updates
  package.json
  yarn.lock
Labels: team/saturn

#2029 Applying 1.12 (SM 1.1) CVE fixes to master
  package.json
  yarn.lock
Labels: library change, team/saturn

#2030 Trivial: move travis ci to node.js 14 (LTS)
  .travis.yml
Labels: team/saturn

#2026 Add tooltip info to the "Requests Per Second" edge label option
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
  src/services/GraphDataSource.ts
  src/types/Graph.ts
Labels: team/saturn

#2035 [v1.26] backport of fix for empty pod logs
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
Labels: team/saturn

#2037 Add graph display option to optionally show idle edges
  src/actions/ActionKeys.ts
  src/actions/GraphToolbarActions.ts
  src/app/History.ts
  src/assets/img/legend/node-color-idle.svg
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/components/CytoscapeGraph/EmptyGraphLayout.tsx
  src/components/CytoscapeGraph/MiniGraphCard.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/Nav/NavUtils.tsx
  src/pages/Graph/GraphHelpFind.tsx
  src/pages/Graph/GraphLegendData.ts
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx
  src/pages/Graph/GraphToolbar/__tests__/__snapshots__/GraphLegend.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
  src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentInfoDescription.tsx
  src/reducers/GraphDataState.ts
  src/reducers/__tests__/GraphDataState.test.ts
  src/services/GraphDataSource.ts
  src/services/__tests__/GraphDataSource.test.ts
  src/store/Selectors.ts
  src/store/Selectors/GraphData.ts
  src/store/Store.ts
  src/types/Graph.ts
Labels: backend changes required, team/saturn

#2041 For Github actions CI add caching to reduce build time (a bunch)
  .github/workflows/ci.yml
Labels: team/saturn
