Repository kiali/kiali-ui, pull requests merged in 2020-04, with the labels that each got.

#1719 Ellipsis on cards of overview page when namespace name is too large
  src/pages/Overview/OverviewPage.tsx
Labels: team/saturn

#1720 Graph: Merge edge options into display dropdown to limit toolbar wrap
  src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/components/Pf/PfColors.tsx
  src/pages/Graph/GraphHelpTour.ts
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  src/pages/Graph/_Graph.scss
Labels: team/saturn

#1705 Better wording for Dropdown menus
  src/components/DurationDropdown/DurationDropdown.tsx
  src/components/Health/__tests__/__snapshots__/HealthDetails.test.tsx.snap
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/components/Time/TimeControls.tsx
  src/components/Time/TimeRangeComponent.tsx
  src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
  src/config/ServerConfig.ts
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/AppList/AppListComponent.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
  src/pages/WorkloadList/WorkloadListComponent.tsx
Labels: team/saturn

#1729 [v1.15] Fix graph error when enabling response time edges in some cases. (#1715)
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
Labels: backport/v1.15, team/saturn

#1731 Better font sizing and positioning in Overview page
  src/pages/Overview/OverviewCardContentExpanded.tsx
  src/pages/Overview/OverviewCardSparkline.tsx
Labels: team/saturn

#1721 Upgrade the 'kind-of' library for vulnerability. (Medium)
  package.json
  yarn.lock
Labels: team/saturn

#1743 Add timer refresh to list pages
  src/pages/AppList/AppListComponent.tsx
  src/pages/ServiceList/ServiceListComponent.tsx
  src/pages/WorkloadList/WorkloadListComponent.tsx
  src/pages/extensions/iter8/Iter8ExperimentList/ExperimentListContainer.tsx
Labels: team/saturn

#1726 Upgrade PF4 stuff to release 2020.04
  package.json
  src/components/ToolbarDropdown/__tests__/__snapshots__/ToolbarDropdown.test.tsx.snap
  src/components/Tour/TourStop.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigNew/GatewayForm.tsx
  src/pages/IstioConfigNew/SidecarForm.tsx
  src/pages/Login/LoginPage.tsx
  yarn.lock
Labels: dependencies, library change

#1725 Graph toolbar use custom secondary masthead
  src/components/Nav/SecondaryMasthead.tsx
  src/pages/Graph/GraphHelpFind.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/GraphToolbar/GraphSecondaryMasthead.tsx
  src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  src/routes.tsx
Labels: team/saturn

#1744 Split the workload logging tab into pod logs and container logs
  package.json
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPodLogs.tsx
  yarn.lock
Labels: team/saturn

#1747 Add AuthorizationPolicy form
  src/components/IstioWizards/IstioWizardActions.ts
  src/pages/IstioConfigNew/AuthorizationPolicyForm.tsx
  src/pages/IstioConfigNew/AuthorizationPolicyForm/From/SourceBuilder.tsx
  src/pages/IstioConfigNew/AuthorizationPolicyForm/From/SourceList.tsx
  src/pages/IstioConfigNew/AuthorizationPolicyForm/RuleBuilder.tsx
  src/pages/IstioConfigNew/AuthorizationPolicyForm/RuleList.tsx
  src/pages/IstioConfigNew/AuthorizationPolicyForm/To/OperationBuilder.tsx
  src/pages/IstioConfigNew/AuthorizationPolicyForm/To/OperationList.tsx
  src/pages/IstioConfigNew/AuthorizationPolicyForm/When/ConditionBuilder.tsx
  src/pages/IstioConfigNew/AuthorizationPolicyForm/When/ConditionList.tsx
  src/pages/IstioConfigNew/IstioConfigNewPage.tsx
  src/types/IstioObjects.ts
Labels: backend changes required

#1742 Graph Hide can crash on graph refresh
  src/actions/ActionKeys.ts
  src/actions/GraphActions.ts
  src/actions/GraphDataActions.ts
  src/actions/GraphThunkActions.ts
  src/actions/KialiAppAction.ts
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/MiniGraphCard.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx
  src/reducers/GraphDataState.ts
  src/reducers/__tests__/GraphDataState.test.ts
  src/services/GraphDataSource.ts
  src/services/__tests__/GraphDataSource.test.ts
  src/store/Store.ts
  src/types/Graph.ts
Labels: team/saturn

#1754 Fix issue zoom/pan/fit and graph-hide
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/pages/Graph/GraphToolbar/GraphFind.tsx
Labels: team/saturn

#1752 Allow pre-set query params in Grafana URL
  src/components/Metrics/GrafanaLinks.tsx
  src/components/Metrics/__tests__/GrafanaLinks.test.ts
Labels: backend changes required

#1733 Add Istio component status into masthead
  src/actions/ActionKeys.ts
  src/actions/IstioStatusActions.ts
  src/actions/KialiAppAction.ts
  src/components/IstioStatus/IstioComponentStatus.tsx
  src/components/IstioStatus/IstioStatus.scss
  src/components/IstioStatus/IstioStatus.tsx
  src/components/IstioStatus/IstioStatusList.tsx
  src/components/IstioStatus/__tests__/IstioComponentStatus.test.tsx
  src/components/IstioStatus/__tests__/IstioStatus.test.tsx
  src/components/IstioStatus/__tests__/IstioStatusList.test.tsx
  src/components/IstioStatus/__tests__/__snapshots__/IstioComponentStatus.test.tsx.snap
  src/components/IstioStatus/__tests__/__snapshots__/IstioStatus.test.tsx.snap
  src/components/IstioStatus/__tests__/__snapshots__/IstioStatusList.test.tsx.snap
  src/components/MTls/MeshMTLSStatus.tsx
  src/components/Nav/Masthead/HelpDropdown.tsx
  src/components/Nav/Masthead/Masthead.tsx
  src/config/Config.ts
  src/reducers/IstioStatusState.ts
  src/reducers/index.ts
  src/services/Api.ts
  src/store/ConfigStore.ts
  src/store/Selectors.ts
  src/store/Store.ts
  src/types/IstioStatus.ts
Labels: backend changes required

#1756 Don't offer kebab navigation in summary panel for inaccessible nodes.
  src/pages/Graph/SummaryPanelNode.tsx
Labels: team/saturn

#1730 Allow multiple metrics per chart
  package.json
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/Helper.ts
  src/components/Metrics/__tests__/IstioMetrics.test.tsx
  src/services/__tests__/ApiMethods.test.tsx.ts
  yarn.lock
Labels: backend changes required, library change

#1762 Remove unnecessary deps
  package.json
  yarn.lock
Labels: team/saturn
