Repository kiali/kiali-ui, pull requests merged in 2020-02, with the labels that each got.

#1642 [Metrics] Clicking on a span should lead to Traces view
  package.json
  src/app/History.ts
  src/components/Metrics/IstioMetrics.tsx
  src/components/Metrics/SpanOverlay.ts
  src/pages/ServiceDetails/ServiceTraces.tsx
  yarn.lock
Labels: library change

#1646 Show Istio Config status only when objects present. Show # objects counted
  src/components/Validations/ValidationSummary.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Overview/OverviewPage.tsx
  src/types/IstioObjects.ts
Labels: backend changes required

#1645 Reworked some jaeger error handling
  src/actions/ActionKeys.ts
  src/actions/JaegerActions.ts
  src/actions/__tests__/JaegerActions.test.ts
  src/app/AuthenticationController.tsx
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/IstioMetrics.tsx
  src/components/Metrics/SpanOverlay.ts
  src/components/Nav/Menu.tsx
  src/components/Nav/Navigation.tsx
  src/config/Config.ts
  src/pages/Graph/SummaryPanelGroup.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceTraces.tsx
  src/reducers/JaegerState.ts
  src/reducers/__tests__/JaegerStateReducer.test.ts
  src/services/Api.ts
  src/store/Store.ts
  src/types/JaegerInfo.ts
  src/types/ServiceInfo.ts
Labels: backend changes required

#1650 Move Nav to PF4 style
  src/components/Nav/Menu.tsx
  src/components/Nav/Navigation.scss
  src/components/Nav/_Menu.scss
  src/styles/_overrides.scss
  src/styles/index.scss
Labels: backport/v1.12, ux review required

#1652 For non-istio apps make correct the namespace/validation spacing
  src/pages/Graph/SummaryPanelGraph.tsx
Labels: team/saturn

#1637 Read server config for 3scale rendering
  src/components/IstioWizards/ThreeScaleIntegration.tsx
  src/components/Nav/Menu.tsx
  src/components/Nav/RenderPage.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/extensions/threescale/ThreeScaleHandlerDetails/ThreeScaleHandlerDetailsPage.tsx
  src/pages/extensions/threescale/ThreeScaleHandlerList/ThreeScaleHandlerListPage.tsx
  src/routes.tsx
  src/types/ServerConfig.ts
Labels: backend changes required

#1653 In-chart time navigation with brush container
  package.json
  src/app/__tests__/App.test.tsx
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/IstioMetrics.tsx
  src/components/Time/TimeRangeComponent.tsx
  src/setupTests.ts
  yarn.lock
Labels: library change

#1612 Add a whitelist for services in istio-system
  src/actions/__tests__/JaegerActions.test.ts
  src/components/JaegerIntegration/JaegerResults/SpanTable.tsx
  src/reducers/JaegerState.ts
  src/reducers/__tests__/JaegerStateReducer.test.ts
  src/types/JaegerInfo.ts
Labels: backport/v1.12

#1660 Focus animation changes
  src/app/History.ts
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  src/utils/SearchParamUtils.ts
Labels: team/saturn

#1641 Decouple data of CytoscapeGraph component from redux
  package.json
  src/actions/ActionKeys.ts
  src/actions/GraphDataActions.ts
  src/actions/GraphDataThunkActions.ts
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/EmptyGraphLayout.tsx
  src/pages/Graph/GraphPage.tsx
  src/reducers/GraphDataState.ts
  src/reducers/__tests__/GraphDataState.test.ts
  src/services/GraphDataSource.ts
  src/services/__tests__/GraphDataSource.test.ts
  src/store/Selectors.ts
  src/store/Selectors/GraphData.ts
  src/store/Store.ts
  yarn.lock
Labels: library change, refactor, team/saturn

#1662 Support Weigthed Routing Wizard when workloads are added/removed
  src/components/IstioWizards/IstioWizardActions.ts
  src/components/IstioWizards/WeightedRouting.tsx
Labels: team/jupiter

#1663 Decouple settings of CytoscapeGraph component from redux
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/EmptyGraphLayout.tsx
  src/pages/Graph/GraphPage.tsx
Labels: refactor, team/saturn

#1666 Double-click focus node to navigate to detail
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
Labels: team/saturn

#1671 Use "auto" tooltip positioning for graph side panel
  src/pages/Graph/SummaryLink.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
Labels: team/saturn

#1667 Merge "api doc" and "additional details" features
  package.json
  src/assets/img/graphql-logo.svg
  src/assets/img/grpc-logo.svg
  src/assets/img/rest-logo.svg
  src/components/ApiDocumentation/ApiDocumentation.tsx
  src/components/ApiDocumentation/ApiTypeIndicator.tsx
  src/components/ApiDocumentation/__tests__/ApiDocumentation.test.tsx
  src/components/ApiDocumentation/__tests__/ApiTypeIndicator.test.tsx
  src/components/ApiDocumentation/__tests__/__snapshots__/ApiDocumentation.test.tsx.snap
  src/components/Logo/Logos.tsx
  src/components/VirtualList/Renderers.tsx
  src/config/Config.ts
  src/config/Logos.ts
  src/config/index.ts
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceMock.ts
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/pages/ServiceList/FiltersAndSorts.ts
  src/pages/ServiceList/ServiceListComponent.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
  src/pages/WorkloadList/FiltersAndSorts.ts
  src/pages/WorkloadList/WorkloadListComponent.tsx
  src/services/__mockData__/getServiceDetail.ts
  src/types/ServiceInfo.ts
  src/types/ServiceList.ts
  src/types/Workload.ts
  yarn.lock
Labels: backend changes required

#1670 Implement mini-graph on detail pages
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/EmptyGraphLayout.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/pages/AppDetails/AppDetailsPage.tsx
  src/pages/AppDetails/AppInfo.tsx
  src/pages/AppDetails/AppInfo/AppDescription.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/ServiceDetails/ServiceDetailsPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoDescription.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
  src/pages/ServiceDetails/__tests__/__snapshots__/ServiceInfo.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/WorkloadDescription.test.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
Labels: team/saturn

#1675 Move react-scripts as a devDependency
  package.json
Labels: team/saturn
