Repository kiali/kiali-ui, pull requests merged in 2021-06, with the labels that each got.

#2168 Get the trace span selections to be visible by getting the h-scroll i…
  src/pages/Graph/SummaryPanelTraceDetails.tsx
Labels: team/saturn

#2165 Add kiali traffic scenario graph badges to Services
  src/actions/ActionKeys.ts
  src/actions/GraphToolbarActions.ts
  src/assets/img/legend/node-badge-fault-injection.svg
  src/assets/img/legend/node-badge-request-timeout.svg
  src/assets/img/legend/node-badge-traffic-shifting.svg
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/components/CytoscapeGraph/MiniGraphCard.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/CytoscapeGraph/graphs/__tests__/GraphStyles.test.ts
  src/config/Icons.ts
  src/config/KialiIcon.tsx
  src/pages/Graph/GraphHelpFind.tsx
  src/pages/Graph/GraphLegendData.ts
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx
  src/pages/Graph/GraphToolbar/__tests__/__snapshots__/GraphLegend.test.tsx.snap
  src/pages/Graph/SummaryPanelNode.tsx
  src/reducers/GraphDataState.ts
  src/reducers/__tests__/GraphDataState.test.ts
  src/store/Selectors/GraphData.ts
  src/store/Store.ts
  src/types/Graph.ts
Labels: backend changes required, team/saturn

#2172 Ensure that Health calculations for graph use correct time period
  src/pages/Overview/OverviewPage.tsx
  src/services/Api.ts
  src/services/GraphDataSource.ts
Labels: backend changes required, team/saturn

#2163 Upgrade tippy dependency to latest version
  package.json
  src/app/App.tsx
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/CytoscapeGraph/CytoscapeContextMenu.tsx
  yarn.lock
Labels: team/saturn

#2173 Wrapper for icon tooltips
  src/components/Health/HealthIndicator.tsx
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/components/TrafficList/TrafficListComponent.tsx
  src/config/KialiIcon.tsx
Labels: team/saturn

#2171 Added new Warning message on workload pod in case of failing containers.
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/types/IstioObjects.ts
Labels: backend changes required

#2174 Show CB badge even when no VS present
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/CytoscapeGraph/graphs/__tests__/GraphStyles.test.ts
Labels: team/saturn

#2177 Display throughput on the graph edges
  src/actions/ActionKeys.ts
  src/actions/GraphToolbarActions.ts
  src/actions/__tests__/GraphToolbarAction.test.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/components/CytoscapeGraph/MiniGraphCard.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/Nav/NavUtils.tsx
  src/pages/Graph/GraphHelpFind.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx
  src/reducers/GraphDataState.ts
  src/reducers/__tests__/GraphDataState.test.ts
  src/services/GraphDataSource.ts
  src/services/__tests__/GraphDataSource.test.ts
  src/store/Selectors.ts
  src/store/Selectors/GraphData.ts
  src/store/Store.ts
  src/types/Graph.ts
Labels: backend changes required, team/saturn

#2180 remove istio_component_namespaces config
  src/config/ServerConfig.ts
  src/types/ErrorRate/__testData__/ErrorRateConfig.ts
  src/types/ServerConfig.ts
  src/types/__testData__/HealthConfig.ts
Labels: backend changes required, team/saturn

#2183 Sort sublists details pages
  src/components/Details/DetailDescription.tsx
  src/components/IstioConfigCard/IstioConfigCard.tsx
  src/components/IstioConfigCard/__tests__/IstioConfigCard.test.tsx
  src/components/IstioConfigCard/__tests__/__snapshots__/IstioConfigCard.test.tsx.snap
  src/pages/ServiceDetails/ServiceDescription.tsx
  src/pages/WorkloadDetails/WorkloadPods.tsx
Labels: backport/v1.36, team/jupiter

#2186 Fix sync state on URL on Metrics tab
  src/components/Metrics/CustomMetrics.tsx
  src/components/Metrics/IstioMetrics.tsx
  src/components/MetricsOptions/MetricsSettingsDropdown.tsx
Labels: backport/v1.36

#2187 Fix duplicate container options in workload pod logs
  src/pages/WorkloadDetails/WorkloadPodLogs.tsx
Labels: backport/v1.36, team/saturn
