Repository kiali/kiali-ui, pull requests merged in 2021-05, with the labels that each got.

#2138 Adjust list/details layout and title
  src/components/Details/DetailDescription.tsx
  src/components/VirtualList/Config.ts
  src/components/VirtualList/Renderers.tsx
Labels: team/jupiter

#2139 Application Traffic - some outbound traffic is not shown
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/MiniGraphCard.tsx
  src/pages/AppDetails/AppInfo.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/services/GraphDataSource.ts
Labels: team/saturn

#2140 Fix SE column title
  src/pages/IstioConfigNew/ServiceEntryForm.tsx
Labels: team/jupiter

#2141 Protect against code-drop-through
  src/pages/Graph/GraphToolbar/GraphToolbar.tsx
Labels: team/saturn

#2151 Don't include the home cluster among remote clusters when checking for external URLs
  src/app/AuthenticationController.tsx
Labels: team/saturn

#2150 Add namespace to istio error toaster message
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
Labels: team/saturn

#2156 Add sourceprincipal and destprincipal operands to Graph Find/Hide.
  src/pages/Graph/GraphHelpFind.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/GraphToolbar/__tests__/GraphFind.test.tsx
Labels: team/saturn

#2146 Fix ServiceEntry graph links
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/pages/Graph/SummaryLink.tsx
  src/types/Graph.ts
Labels: backend changes required, team/saturn

#2157 [v1.34] Don't include the home cluster among remote clusters when checking for external URLs
  src/app/AuthenticationController.tsx
Labels: team/saturn

#2155 Update to using new isProxy flag to identify proxy containers for logs view
  src/pages/WorkloadDetails/WorkloadPodLogs.tsx
  src/types/IstioObjects.ts
Labels: backend changes required, team/saturn

#2145 Deprecate publishing to NPM (front-end)
  .env.downstream
  .env.upstream
  Makefile.jenkins
  README.adoc
  RELEASING.adoc
  package.json
Labels: team/saturn

#2162 Hide Logout option for auth strategies that don't support it
  src/components/Nav/Masthead/UserDropdown.tsx
Labels: team/saturn

#2159 Introduce Find/Hide presets
  src/pages/Graph/GraphHelpFind.tsx
  src/pages/Graph/GraphHelpTour.ts
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/GraphToolbar/GraphFindOptions.tsx
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/pages/Graph/_Graph.scss
  src/types/ServerConfig.ts
Labels: backend changes required, team/saturn
