Repository kiali/kiali-ui, pull requests merged in 2021-04, with the labels that each got.

#2121 In Metrics spans disappear in mouseOver
  src/components/Charts/ChartWithLegend.tsx
Labels: team/jupiter

#2119 Allow nav from detail view mini-graph to graph page node graph.
  src/components/CytoscapeGraph/MiniGraphCard.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphToolbar/GraphSecondaryMasthead.tsx
  src/pages/Graph/GraphToolbar/GraphToolbar.tsx
Labels: team/saturn

#2104 Enhanced logs view with access log detail
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/Envoy/AccessLogModal.tsx
  src/components/Pf/PfColors.tsx
  src/config/KialiIcon.tsx
  src/pages/Graph/SummaryLink.tsx
  src/pages/Graph/SummaryPanelClusterBox.tsx
  src/pages/WorkloadDetails/WorkloadPodLogs.tsx
  src/services/Api.ts
  src/types/IstioObjects.ts
Labels: backend changes required, team/saturn

#2125 Fix annoying "blocked" pointer when hovering on graph settings dropdown.
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/styles/DropdownStyles.ts
Labels: team/saturn

#2118 Navigation to remote Kialis from graph context menu and side panel
  .travis.yml
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/Link/KialiPageLink.tsx
  src/config/ServerConfig.ts
  src/pages/Graph/SummaryLink.tsx
  src/pages/Graph/SummaryPanelAppBox.tsx
  src/pages/Graph/SummaryPanelClusterBox.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/types/ErrorRate/__testData__/ErrorRateConfig.ts
  src/types/ServerConfig.ts
  src/types/__testData__/HealthConfig.ts
Labels: backend changes required, team/saturn

#2123 Only show DR link to host when no checkers presents
  src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleOverview.tsx
Labels: team/jupiter

#2129 Ensure serverConfig has proper defaults
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/Link/KialiPageLink.tsx
  src/components/Nav/Masthead/Masthead.tsx
  src/components/Nav/Navigation.tsx
  src/config/ServerConfig.ts
Labels: team/saturn

#2130 [backport v1.33] Ensure serverConfig has proper defaults (#2129)
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/Link/KialiPageLink.tsx
  src/components/Nav/Masthead/Masthead.tsx
  src/components/Nav/Navigation.tsx
  src/config/ServerConfig.ts
Labels: team/saturn

#2124 Consolidate terminology on inbound/outbound
  src/components/CytoscapeGraph/CytoscapeTrace.ts
  src/components/CytoscapeGraph/graphs/GraphHighlighter.ts
  src/components/TrafficList/TrafficListComponent.tsx
  src/pages/Graph/GraphHelpFind.tsx
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/pages/Graph/SummaryPanelAppBox.tsx
  src/pages/Graph/SummaryPanelClusterBox.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Graph/SummaryPanelNamespaceBox.tsx
  src/pages/Graph/SummaryPanelNodeTraffic.tsx
  src/pages/extensions/iter8/Iter8ExperimentDetails/TrafficControlInfo.tsx
Labels: team/saturn

#2126 Improve graph node labels and PF badging
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/MiniGraphCard.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/IstioWizards/RequestRouting/Rules.tsx
  src/components/IstioWizards/TrafficShifting.tsx
  src/components/Link/IstioObjectLink.tsx
  src/components/Pf/PfBadges.tsx
  src/components/Pf/PfColors.tsx
  src/components/TrafficList/TrafficListComponent.tsx
  src/components/VirtualList/Config.ts
  src/components/VirtualList/Renderers.tsx
  src/components/VirtualList/VirtualItem.tsx
  src/components/VirtualList/_VirtualList.scss
  src/pages/Graph/SummaryLink.tsx
  src/pages/Graph/SummaryPanelClusterBox.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Graph/SummaryPanelNamespaceBox.tsx
  src/pages/WorkloadDetails/WorkloadPodLogs.tsx
  src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentInfoDescription.tsx
  src/pages/extensions/iter8/Iter8ExperimentDetails/ExperimentRules.tsx
  src/pages/extensions/iter8/Iter8ExperimentList/ExperimentListPage.tsx
  src/types/Graph.ts
Labels: team/saturn

#2122 Overview tabs refactoring
  src/components/CytoscapeGraph/EmptyGraphLayout.tsx
  src/components/CytoscapeGraph/MiniGraphCard.tsx
  src/components/Details/DetailDescription.tsx
  src/components/Health/HealthDetails.tsx
  src/components/Health/HealthIndicator.tsx
  src/components/Health/__tests__/HealthDetails.test.tsx
  src/components/Health/__tests__/HealthIndicator.test.tsx
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/components/IstioConfigCard/IstioConfigCard.tsx
  src/components/IstioConfigSubList/IstioConfigSubList.tsx
  src/components/Label/Labels.tsx
  src/components/Label/__tests__/__snapshots__/Labels.test.tsx.snap
  src/components/MissingSidecar/MissingSidecar.tsx
  src/components/Nav/Page/RenderComponentScroll.tsx
  src/components/Time/LocalTime.tsx
  src/components/VirtualList/Renderers.tsx
  src/pages/AppDetails/AppDescription.tsx
  src/pages/AppDetails/AppInfo.scss
  src/pages/AppDetails/AppInfo.tsx
  src/pages/AppDetails/AppInfo/AppDescription.scss
  src/pages/AppDetails/AppInfo/AppDescription.tsx
  src/pages/Graph/SummaryLink.tsx
  src/pages/Overview/OverviewStatus.tsx
  src/pages/ServiceDetails/ServiceDescription.tsx
  src/pages/ServiceDetails/ServiceInfo.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.scss
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoDescription.tsx
  src/pages/ServiceDetails/ServiceInfo/ServiceInfoWorkload.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoDescription.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceInfoWorkloads.test.tsx
  src/pages/ServiceDetails/ServiceInfo/__tests__/ServiceMock.ts
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoDescription.test.tsx.snap
  src/pages/ServiceDetails/ServiceInfo/__tests__/__snapshots__/ServiceInfoWorkloads.test.tsx.snap
  src/pages/ServiceDetails/ServiceNetwork.tsx
  src/pages/ServiceDetails/__tests__/ServiceInfo.test.tsx
  src/pages/WorkloadDetails/PodStatus.tsx
  src/pages/WorkloadDetails/ProxyStatusList.tsx
  src/pages/WorkloadDetails/WorkloadDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo.tsx
  src/pages/WorkloadDetails/WorkloadInfo/PodStatus.scss
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadDescription.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadPods.tsx
  src/pages/WorkloadDetails/WorkloadInfo/WorkloadServices.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/WorkloadDescription.test.tsx
  src/pages/WorkloadDetails/WorkloadInfo/__tests__/__snapshots__/WorkloadDescription.test.tsx.snap
  src/pages/WorkloadDetails/WorkloadPods.tsx
  src/pages/WorkloadDetails/__tests__/ProxyStatusList.test.tsx
  src/pages/WorkloadDetails/__tests__/__snapshots__/ProxyStatusList.test.tsx.snap
  src/services/GraphDataSource.ts
  src/types/Health.ts
Labels: team/jupiter

#2131 Friendly error messages for OpenID
  src/pages/Login/LoginPage.tsx
Labels: team/saturn

#2133 Adjust Envoy details
  src/components/Envoy/EnvoyModal.tsx
  src/components/Envoy/tables/BaseTable.tsx
  src/components/Filters/StatefulFilters.tsx
Labels: team/jupiter

#2134 Improve handling when adding cluster discriminators to graph node labels
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/pages/Graph/SummaryLink.tsx
  src/types/Graph.ts
Labels: team/saturn
