Repository kiali/kiali-ui, pull requests merged in 2021-07, with the labels that each got.

#2193 [v1.36] Fix duplicate container options in workload pod logs
  src/pages/WorkloadDetails/WorkloadPodLogs.tsx
Labels: backport/v1.36, team/saturn

#2190 Fix missing mount Envoy tabs
  src/components/Envoy/EnvoyDetails.tsx
Labels: backport/v1.36

#2192 Show Istio configuration linked with Services and Workloads (and Applications) on list pages
  src/components/VirtualList/Renderers.tsx
  src/helpers/__tests__/LabelFilterHelper.test.ts
  src/pages/AppList/AppListClass.tsx
  src/pages/AppList/FiltersAndSorts.ts
  src/pages/ServiceList/FiltersAndSorts.ts
  src/pages/ServiceList/ServiceListPage.tsx
  src/pages/WorkloadList/FiltersAndSorts.ts
  src/pages/WorkloadList/WorkloadListPage.tsx
  src/types/AppList.ts
  src/types/ServiceList.ts
  src/types/Workload.ts
Labels: backend changes required

#2197 Use workload parameters for custom dashboards
  src/components/Metrics/CustomMetrics.tsx
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/types/MetricsOptions.ts
Labels: backend changes required, backport/v1.36

#2200 Support multiple rows in metrics dashboards
  src/components/Charts/Dashboard.tsx
  src/components/Charts/KChart.tsx
  src/components/Metrics/__tests__/IstioMetrics.test.tsx
  src/stories/__dataStories__/dashboardService.ts
  src/stories/__dataStories__/dashboardWithLegends.ts
  src/stories/__dataStories__/envoyMetrics.ts
  src/types/Dashboards.ts
  src/types/__mocks__/Dashboards.mock.ts
Labels: backport/v1.36

#2181 Add new "Traffic" dropdown to the graph secondary masthead.
  src/actions/ActionKeys.ts
  src/actions/GraphToolbarActions.ts
  src/app/AuthenticationController.tsx
  src/app/History.ts
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
  src/components/CytoscapeGraph/MiniGraphCard.tsx
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/Nav/NavUtils.tsx
  src/components/SummaryPanel/RateTable.tsx
  src/components/SummaryPanel/RpsChart.tsx
  src/pages/Graph/GraphHelpTour.ts
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphToolbar/GraphSecondaryMasthead.tsx
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/pages/Graph/GraphToolbar/GraphToolbar.tsx
  src/pages/Graph/GraphToolbar/GraphTraffic.tsx
  src/pages/Graph/SummaryPanel.tsx
  src/pages/Graph/SummaryPanelAppBox.tsx
  src/pages/Graph/SummaryPanelClusterBox.tsx
  src/pages/Graph/SummaryPanelCommon.tsx
  src/pages/Graph/SummaryPanelEdge.tsx
  src/pages/Graph/SummaryPanelGraph.tsx
  src/pages/Graph/SummaryPanelNamespaceBox.tsx
  src/pages/Graph/SummaryPanelNodeTraffic.tsx
  src/reducers/GraphDataState.ts
  src/reducers/__tests__/GraphDataState.test.ts
  src/services/GraphDataSource.ts
  src/services/__tests__/GraphDataSource.test.ts
  src/store/Selectors.ts
  src/store/Store.ts
  src/styles/DropdownStyles.ts
  src/types/Graph.ts
  src/types/Metrics.ts
  src/types/ServerConfig.ts
  src/utils/Formatter.ts
  src/utils/TrafficRate.ts
Labels: backend changes required, team/saturn

#2205 Make request routing icon the leftmost for consistency
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/CytoscapeGraph/graphs/__tests__/GraphStyles.test.ts
Labels: team/saturn

#2208 Prefix validation message with the now explicit code
  src/components/Validations/GlobalValidation.tsx
  src/components/Validations/ValidationList.tsx
  src/components/Validations/ValidationStack.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceOverview.tsx
  src/types/AceValidations.ts
  src/types/IstioObjects.ts
Labels: backend changes required

#2211 Offer trace-spans in unified workload logs view
  src/pages/WorkloadDetails/WorkloadDetailsPage.tsx
  src/pages/WorkloadDetails/WorkloadPodLogs.tsx
Labels: team/saturn

#2196 Add hostnames list for gateway and virtual service nodes
  src/assets/img/legend/node-badge-gateways.svg
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
  src/components/CytoscapeGraph/graphs/__tests__/GraphStyles.test.ts
  src/config/Config.ts
  src/config/Icons.ts
  src/config/KialiIcon.tsx
  src/pages/Graph/GraphLegendData.ts
  src/pages/Graph/GraphToolbar/__tests__/__snapshots__/GraphLegend.test.tsx.snap
  src/pages/Graph/SummaryLink.tsx
  src/pages/Graph/SummaryPanelNode.tsx
  src/types/Graph.ts
Labels: backend changes required, team/saturn
