Repository kiali/kiali-ui, pull requests merged in 2021-02, with the labels that each got.

#2063 Envoy dump tables - linking services, destination rules, and virtual services to its detail page
  src/components/Envoy/EnvoyModal.tsx
  src/components/Envoy/tables/BaseTable.tsx
  src/components/Envoy/tables/ClusterTable.ts
  src/components/Envoy/tables/ListenerTable.ts
  src/components/Envoy/tables/RouteTable.ts
  src/helpers/EnvoyHelpers.tsx
  src/services/Api.ts
  src/types/IstioObjects.ts
Labels: backend changes required

#2073 Metrics: fix peer namespace segregation
  src/components/Metrics/IstioMetrics.tsx
Labels: backend changes required, team/jupiter

#2066 Redesign tracing page toolbar
  package.json
  src/app/History.ts
  src/components/JaegerIntegration/JaegerScatter.tsx
  src/components/JaegerIntegration/TracesComponent.tsx
  src/components/JaegerIntegration/TracesDisplayOptions.tsx
  src/components/JaegerIntegration/TracesFetcher.ts
  src/pages/Graph/GraphToolbar/GraphSettings.tsx
  src/pages/Graph/_Graph.scss
  src/styles/DropdownStyles.ts
  src/types/Tracing.ts
  src/utils/tracing/TracingHelper.ts
  src/utils/tracing/__tests__/TracingHelper.test.ts
  yarn.lock
Labels: library change

#2071 Prevent duplicate graph fetch on double-click
  src/pages/Graph/GraphPage.tsx
Labels: team/saturn

#2076 Allow user to zoom by dragging a box overlay around an area of the graph
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
Labels: team/saturn

#2077 Fix the graph tour by adding support for multiple stops at one place
  src/components/Tour/TourStop.tsx
  src/pages/Graph/GraphHelpTour.ts
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/SummaryPanel.tsx
Labels: team/saturn

#2078 Fix graph replay regression introduced when removing code that was ca…
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
Labels: team/saturn

#2079 [v1.29] Fix graph replay regression
  src/components/CytoscapeGraph/CytoscapeGraph.tsx
Labels: team/saturn

#2080 Update envoy response flags that we know about
  src/utils/ResponseFlags.ts
Labels: team/saturn

#2081 UI support for UI defaults
  src/app/AuthenticationController.tsx
  src/components/NamespaceDropdown.tsx
  src/config/ServerConfig.ts
  src/types/ServerConfig.ts
Labels: backend changes required, team/saturn

#2056 Allow custom health configuration to be deployed as annotations
  src/components/Health/__tests__/HealthDetails.test.tsx
  src/components/Health/__tests__/HealthIndicator.test.tsx
  src/components/Health/__tests__/__snapshots__/HealthIndicator.test.tsx.snap
  src/components/TrafficList/TrafficDetails.tsx
  src/config/HealthConfig.ts
  src/config/__tests__/HealthConfig.test.ts
  src/pages/ServiceList/__tests__/ServiceListComponent.test.ts
  src/services/GraphDataSource.ts
  src/types/ErrorRate/ErrorRate.ts
  src/types/ErrorRate/GraphEdgeStatus.ts
  src/types/ErrorRate/TrafficHealth.ts
  src/types/ErrorRate/__testData__/ErrorRateConfig.ts
  src/types/ErrorRate/__tests__/ErrorRate.test.ts
  src/types/ErrorRate/__tests__/ErrorRateBattery.test.ts
  src/types/ErrorRate/__tests__/GraphEdgeStatus.test.ts
  src/types/ErrorRate/__tests__/TrafficHealth.test.ts
  src/types/ErrorRate/__tests__/utils.test.ts
  src/types/ErrorRate/utils.ts
  src/types/Graph.ts
  src/types/Health.ts
  src/types/HealthAnnotation.ts
  src/types/__tests__/Health.test.ts
  src/types/__tests__/HealthAnnotation.test.ts
Labels: backend changes required, team/jupiter
