Repository kiali/kiali-ui, pull requests merged in 2022-03, with the labels that each got.

#2317 Don't show Envoy metrics tab if those are not present
  src/components/Envoy/EnvoyDetails.tsx
Labels: backport/v1.47

#2315 Support 'name.namespace' key for Istio config validation result instead of 'name' only, to support multiple namespaces
  src/types/IstioConfigList.ts
Labels: requires server PR

#2320 Fix time selection issue in replay custom startTime picker
  package.json
  src/components/CytoscapeGraph/ContextMenu/NodeContextMenu.tsx
  src/components/Time/Replay.tsx
  yarn.lock
Labels: requires server PR

#2311 Find/Hide support for Labels
  src/components/CytoscapeGraph/CytoscapeGraphUtils.ts
  src/components/CytoscapeGraph/__tests__/CytoscapeGraph.test.tsx
  src/pages/Graph/GraphHelpFind.tsx
  src/pages/Graph/GraphPage.tsx
  src/pages/Graph/GraphToolbar/GraphFind.tsx
  src/pages/Graph/_Graph.scss
  src/services/GraphDataSource.ts
  src/services/__tests__/GraphDataSource.test.ts
  src/store/Selectors/GraphData.ts
  src/types/Graph.ts
Labels: requires server PR

#2314 Reduce health req lists
  src/components/FilterList/FilterComponent.tsx
  src/components/Filters/CommonFilters.ts
  src/components/TrafficList/TrafficListComponent.tsx
  src/components/VirtualList/Config.ts
  src/components/VirtualList/VirtualItem.tsx
  src/helpers/__tests__/LabelFilterHelper.test.ts
  src/pages/AppList/AppListClass.tsx
  src/pages/AppList/AppListPage.tsx
  src/pages/AppList/FiltersAndSorts.ts
  src/pages/IstioConfigList/FiltersAndSorts.ts
  src/pages/IstioConfigList/__tests__/IstioConfigListComponent.test.ts
  src/pages/ServiceList/FiltersAndSorts.ts
  src/pages/ServiceList/ServiceListPage.tsx
  src/pages/ServiceList/__tests__/ServiceListComponent.test.ts
  src/pages/WorkloadList/FiltersAndSorts.ts
  src/pages/WorkloadList/WorkloadListPage.tsx
  src/services/Api.ts
  src/types/AppList.ts
  src/types/HealthAnnotation.ts
  src/types/ServiceList.ts
  src/types/Workload.ts
Labels: requires server PR

#2299 Side panel re-design for Istio config details page
  src/components/Link/IstioObjectLink.tsx
  src/components/Link/ServiceLink.tsx
  src/components/Link/WorkloadLink.tsx
  src/components/Validations/ValidationObjectSummary.tsx
  src/components/Validations/ValidationSummary.tsx
  src/components/VirtualList/Renderers.tsx
  src/pages/IstioConfigDetails/IstioConfigDetailsPage.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/DestinationRuleOverview.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigHelp.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigOverview.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigReferences.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/IstioConfigValidationReferences.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/IstioObjectDetails.scss
  src/pages/IstioConfigDetails/IstioObjectDetails/IstioStatusMessageList.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/ServiceLink.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceOverview.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/VirtualServiceRoute.tsx
  src/pages/IstioConfigDetails/IstioObjectDetails/__tests__/ServiceLink.test.tsx
  src/services/Api.ts
  src/types/AceValidations.ts
  src/types/IstioConfigDetails.ts
  src/types/IstioObjects.ts
  src/utils/IstioConfigUtils.ts
  yarn.lock
Labels: requires server PR

#2340 [backport v1.36] Improve protection against graph numbers that are actually string variables
  src/components/CytoscapeGraph/graphs/GraphStyles.ts
Labels: backport/v1.36
